## 七月在线机器学习实训营三期第六周(机器学习)考试
#### 考试说明:
- 起止时间：请同学在2018年3月16日至3月18日期间完成，最晚提交时间本周日（3月18日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam6后，进行作答。例如wangwei-exam6
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/4/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>__孙明敏___</u>  
- 批改人： David
- 最终得分:72

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共4题，每题5分，共计20分)

- note: 12

#### 1. 请写出你了解的机器学习特征工程操作，以及它的意义（面试题）
- note: 意义木有写呢。而且相关操作也少了些

1.给类别型的变量进行独热向量编码
2.分段与离散化
3.特征选择

#### 2.请写出上述特征工程操作的sklearn或者pandas实现方式
note: 太少了，随后再补 上~~~~~~

1.sklearn中的onehotencoder pandas中的get_dummies
2.
3.在sklearn中可以使用随机森林选出重要的特征

#### 3.模型评估中的留一法，留出法，交叉验证分别是什么操作？

留一法：假设有N个样本，将每一个样本作为测试样本，其它N-1个样本作为训练样本。这样得到N个分类器，N个测试结果。用这N个结果的平均值来衡量模型的性能。
留出法：将数据集 D 划分为训练集 S 和测试集 T
交叉验证：把数据集D分为k个互斥子集（分层抽样），每次选一个子集作为测试集，其他的集合作为训练集，循环k次，求误差平均值。

#### 4.如何理解模型的过拟合与欠拟合，以及如何解决？（面试题）

欠拟合：首先欠拟合就是模型没有很好地捕捉到数据特征，不能够很好地拟合数据
解决方法：添加其他特征项 减少正则化参数
过拟合：过拟合就是模型把数据学习的太彻底，以至于把噪声数据的特征也学习到了，这样就会导致在后期测试的时候不能够很好地识别数据，即不能正确的分类，模型泛化能力太差。
解决方法：重新清洗数据 增大数据的训练量 采用正则化方法

## 操作题(共1题，共计80分)

### 信用卡欺诈项目(共7项，前5项每题10分，6，7题每题15分)

- note: 60分

- 前期数据导入,预览及处理(此部分勿修改，涉及的数据文件无需复制移动)

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [2]:
data.shape

(112915, 11)

In [3]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [2]:
data.dropna(inplace=True)
data.shapey = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


In [3]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)
y.mean()

0.06742876076872101

- 1.把数据切分成训练集和测试集

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(76053, 10)
(32595, 10)
(76053,)
(32595,)


- 2.使用logistic regression建模，并且输出一下系数，分析重要度。   

- note:分析重要度呢？

In [11]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(penalty='l1', C=0.1)
LR.fit(X_train, y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
LR.coef_#权重系数

array([[-5.36882881e-05, -2.60406763e-02,  4.62107676e-01,
         1.31317710e+00, -9.46974337e-06, -1.80930938e-02,
         3.96290531e-01, -1.70532783e-01, -8.18516992e-01,
         9.97376962e-02]])

In [13]:
LR.intercept_#偏置

array([-1.70224659])

- 3.使用决策树/SVM/KNN...等sklearn分类算法进行分类，尝试了解参数含义，调整不同的参数。

In [28]:
#DT1
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(random_state=0)
dt1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [29]:
#DT2
dt2 = DecisionTreeClassifier(criterion='entropy',splitter='random',random_state=0)
dt2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='random')

In [18]:
#svm1
from sklearn.svm import LinearSVC
svm1 = LinearSVC(random_state=0)
svm1.fit(X_train,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=0)

In [21]:
#svm2
svm2 =LinearSVC(C=0.5,loss='hinge',random_state=0)
svm2.fit(X_train,y_train)

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=0, tol=0.0001, verbose=0)

In [22]:
#svm3
svm3 = LinearSVC(C=0.8,penalty='l2',loss='hinge',random_state=0)
svm3.fit(X_train,y_train)

LinearSVC(C=0.8, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=0, tol=0.0001, verbose=0)

In [23]:
#knn1
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=6)
knn1.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [25]:
#knn2
knn2 = KNeighborsClassifier(algorithm='kd_tree',weights='distance')
knn2.fit(X_train,y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

In [26]:
#knn3
knn3 = KNeighborsClassifier(algorithm='ball_tree',weights='distance',leaf_size=35)
knn3.fit(X_train,y_train)

KNeighborsClassifier(algorithm='ball_tree', leaf_size=35, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

- 4.在测试集上进行预测，计算准确度

In [27]:
#LR
print('LR training accuracy：',LR.score(X_train,y_train))
print('LR test accuracy:',LR.score(X_test,y_test))

LR training accuracy： 0.9329809474971401
LR test accuracy: 0.9337014879582758


In [30]:
#DT
print("DT training accuracy:",dt1.score(X_train,y_train))
print("DT test accuracy:",dt1.score(X_test,y_test))
#?????????是不是过拟合了???????

DT training accuracy: 1.0
DT test accuracy: 0.8933271974229177


In [31]:
#svm
print('SVM training accuracy:',svm3.score(X_train,y_train))
print('SVM test accuracy:',svm3.score(X_test,y_test))

SVM training accuracy: 0.9284051911167213
SVM test accuracy: 0.9292836324589661


In [32]:
#knn
print('KNN training accuracy:',knn2.score(X_train,y_train))
print('KNN test accuracy:',knn2.score(X_test,y_test))

KNN training accuracy: 1.0
KNN test accuracy: 0.9305108145421077


- 5.查看sklearn的官方说明，了解混淆矩阵等评估标准，并对此例进行评估。

In [50]:
#个人理解：混淆矩阵是个n*n的矩阵
#对LR评估
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
y_pred1 = LR.predict(X_test)
y_true1 = y_test
print(confusion_matrix(y_true1, y_pred1))
print(classification_report(y_true=y_true1, y_pred=y_pred1))

[[30366    58]
 [ 2103    68]]
             precision    recall  f1-score   support

          0       0.94      1.00      0.97     30424
          1       0.54      0.03      0.06      2171

avg / total       0.91      0.93      0.91     32595



In [51]:
#对DT评估
y_pred2 = dt2.predict(X_test)
y_true2 = y_test
print(confusion_matrix(y_true2, y_pred2))
print(classification_report(y_true=y_true2, y_pred=y_pred2))

[[28498  1926]
 [ 1603   568]]
             precision    recall  f1-score   support

          0       0.95      0.94      0.94     30424
          1       0.23      0.26      0.24      2171

avg / total       0.90      0.89      0.90     32595



In [52]:
#对SVM评估
y_pred3 = svm2.predict(X_test)
y_true3 = y_test
print(confusion_matrix(y_true3, y_pred3))
print(classification_report(y_true=y_true3, y_pred=y_pred3))

[[30407    17]
 [ 2166     5]]
             precision    recall  f1-score   support

          0       0.93      1.00      0.97     30424
          1       0.23      0.00      0.00      2171

avg / total       0.89      0.93      0.90     32595



In [53]:
#对KNN评估
y_pred4 = knn3.predict(X_test)
y_true4 = y_test
print(confusion_matrix(y_true4, y_pred4))
print(classification_report(y_true=y_true4, y_pred=y_pred4))

[[30295   129]
 [ 2136    35]]
             precision    recall  f1-score   support

          0       0.93      1.00      0.96     30424
          1       0.21      0.02      0.03      2171

avg / total       0.89      0.93      0.90     32595



- 6.银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。   
比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”   
试试看把阈值设定为0.3，再看看这个时候的混淆矩阵等评估指标。

In [56]:
#LR
y_pred_pro1 = LR.predict_proba(X_test)
y_pred5 = y_pred_pro1[:,1]>0.3
y_true5 = y_test
print(confusion_matrix(y_true5, y_pred5))
print(classification_report(y_true=y_true5, y_pred=y_pred5))

[[30230   194]
 [ 1978   193]]
             precision    recall  f1-score   support

          0       0.94      0.99      0.97     30424
          1       0.50      0.09      0.15      2171

avg / total       0.91      0.93      0.91     32595



In [57]:
#dt
y_pred_pro2 = dt2.predict_proba(X_test)
y_pred6 = y_pred_pro2[:,1]>0.3
y_true6 = y_test
print(confusion_matrix(y_true6, y_pred6))
print(classification_report(y_true=y_true6, y_pred=y_pred6))

[[28498  1926]
 [ 1603   568]]
             precision    recall  f1-score   support

          0       0.95      0.94      0.94     30424
          1       0.23      0.26      0.24      2171

avg / total       0.90      0.89      0.90     32595



- note: 是这个方法不提供这种方法。可以参照 其它同学的SVC，输出来制作混淆矩阵

In [58]:
#svm
y_pred_pro3 = svm2.predict_proba(X_test)
y_pred7 = y_pred_pro3[:,1]>0.3
y_true7 = y_test
print(confusion_matrix(y_true7, y_pred7))
print(classification_report(y_true=y_true7, y_pred=y_pred7))
#为什么svm不能输出概率？？？？？？？？

AttributeError: 'LinearSVC' object has no attribute 'predict_proba'

In [59]:
#knn
y_pred_pro4 = knn3.predict_proba(X_test)
y_pred8 = y_pred_pro1[:,1]>0.3
y_true8 = y_test
print(confusion_matrix(y_true8, y_pred8))
print(classification_report(y_true=y_true8, y_pred=y_pred8))

[[30230   194]
 [ 1978   193]]
             precision    recall  f1-score   support

          0       0.94      0.99      0.97     30424
          1       0.50      0.09      0.15      2171

avg / total       0.91      0.93      0.91     32595



- 7.尝试对不同特征的重要度进行排序，通过特征选择的方式，对特征进行筛选。并重新建模，观察此时的模型准确率等评估指标。

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
feat_labels = data.columns[1:]
forest = RandomForestClassifier(n_estimators=10000,
                                random_state=0)
                                
forest.fit(X_train, y_train)
importances = forest.feature_importances_
indices = np.argsort(importances)[::-1]

for f in range(X_train.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30, 
                            feat_labels[indices[f]], 
                            importances[indices[f]]))

plt.title('Feature Importances')
plt.bar(range(X_train.shape[1]), 
        importances[indices],
        color='lightblue', 
        align='center')

plt.xticks(range(X_train.shape[1]), 
           feat_labels[indices], rotation=90)
plt.xlim([-1, X_train.shape[1]])
plt.tight_layout()
#plt.savefig('./random_forest.png', dpi=300)
plt.show()
#随机森林一直跑不出来

### 本阶段课程意见反馈题(5分送分项，非必答)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


In [ ]:
主要学习了sklearn这个机器学习库 里面的API太多 希望以后自己能多加练习了解了解API 以及各种参数的意思

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

<hr>
<center><h1>####答卷结束####</h1></center>