## 七月在线机器学习实训营三期第六周(机器学习)考试
#### 考试说明:
- 起止时间：请同学在2018年3月16日至3月18日期间完成，最晚提交时间本周日（3月18日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam6后，进行作答。例如wangwei-exam6
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/4/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>__廖莹___</u>  
- 批改人： David
- 最终得分:95

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共4题，每题5分，共计20分)

#### 1. 请写出你了解的机器学习特征工程操作，以及它的意义（面试题）
- note: 优秀20分

* 特征工程操作有： 
  * 1.数据采集/清洗/采样  
  * 2.特征处理  
    特征处理可以归纳为对这几类数据的处理：数值型、类别型、时间型、文本型、统计型、组合特征型    
    特征处理方法有标准化， OneHot 编码，二值化，归一化等
  * 3.特征选择    
    特征选择的方法有过滤型、包裹型、嵌入型
* 特征工程是把原始数据转变为模型的训练数据的过程，它的意义就是获取更好的训练数据特征，使得机器学习模型逼近这个上限。因为好的特征具有更强的灵活性，可以用简单的模型做训练，更可以得到优秀的结果。 

#### 2.请写出上述特征工程操作的sklearn或者pandas实现方式


1.数据采集/清洗/采样等操作可以使用pandas的load、fillna、drop、loc等操作  
2.特征处理可以使用preprocessing包里的StandardScaler，OneHotEncoder，Binarizer，normalize等实现  
3.特征选取可以使用feature_selection包里面的相关方法

#### 3.模型评估中的留一法，留出法，交叉验证分别是什么操作？

* 留一法：特殊的交叉验证。将数据样本分为m折，m就是数据样本的总数。每次取其中一折样本作为测试集，剩余的m-1折为训练集，最后将m个误差结果取均值。留一法的优点是，每次让尽可能多的样本参与训练。
* 留出法：把数据样本随机分为两个互不相交的部分，分别是训练集和测试集。即：把数据样本D分为训练集S和测试集T，其中SUT=D,S∩T=Φ。简单地说就是把数据样本分为两部分即可。 
* 交叉验证：随机地将数据样本切分为n个互不相交大小相同的子集，然后利用n-1 个子集的数据训练模型，利用余下的子集测试模型。

#### 4.如何理解模型的过拟合与欠拟合，以及如何解决？（面试题）

* 欠拟合
模型没有很好地捕捉到数据特征，不能够很好地拟合数据  
*　* 解决方法：
  - 添加其他特征项，例如，“组合”、“泛化”、“相关性”三类特征是特征添加的重要手段，除此之外，“上下文特征”、“平台特征”等等，都可以作为特征添加的首选项。
  - 添加多项式特征，如将线性模型通过添加二次项或者三次项使模型泛化能力更强。
  - 减少正则化参数，模型出现了欠拟合，则需要减少正则化参数。


* 过拟合
指学习时选择的模型所包含的参数过多，以致于出现这一模型对已知数据预测
得很好，但对未知数据预测得很差的现象。即模型把数据学习的太彻底，以至于把噪声数据的特征也学习到了，这样就会导致在后期测试的时候不能够很好地识别测试数据，不能正确的分类，模型泛化能力太差。

*　*解决方法：
  - 重新清洗数据，数据清洗不到位可能导致模型过拟合
  - 增大数据的训练量，训练数据占总数据的比例过小，可能导致过拟合。
  - 采用正则化方法。包括L1正则和L2正则



## 操作题(共1题，共计80分)

- note:75

### 信用卡欺诈项目(共7项，前5项每题10分，6，7题每题15分)

- 前期数据导入,预览及处理(此部分勿修改，涉及的数据文件无需复制移动)

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:#/home/sxy-s3/0.Teacher/Exam/
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [3]:
# data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112915 entries, 0 to 112914
Data columns (total 11 columns):
SeriousDlqin2yrs                        112915 non-null int64
RevolvingUtilizationOfUnsecuredLines    112915 non-null float64
age                                     108648 non-null float64
NumberOfTime30-59DaysPastDueNotWorse    112915 non-null float64
DebtRatio                               112915 non-null float64
MonthlyIncome                           112915 non-null float64
NumberOfOpenCreditLinesAndLoans         112915 non-null float64
NumberOfTimes90DaysLate                 112915 non-null float64
NumberRealEstateLoansOrLines            112915 non-null float64
NumberOfTime60-89DaysPastDueNotWorse    112915 non-null float64
NumberOfDependents                      108648 non-null float64
dtypes: float64(10), int64(1)
memory usage: 10.3 MB


In [10]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [5]:
data.dropna(inplace=True)#去掉带有空值的样本
data.shapey = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

In [6]:
y = data['SeriousDlqin2yrs']# 获得样本label
X = data.drop('SeriousDlqin2yrs', axis=1)# 获得其特征向量
# X.info()
y.mean()
# y

0.06742876076872101

- 1.把数据切分成训练集和测试集

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

- 2.使用logistic regression建模，并且输出一下系数，分析重要度。   

In [108]:
from sklearn.linear_model import LogisticRegression
# 定义逻辑回归模型
LR = LogisticRegression()
LR.fit(X_train,y_train)
LR.coef_[0]


array([ -6.88696735e-05,  -4.59167357e-02,   2.38517280e-01,
         4.36907814e-02,  -4.64590114e-05,  -1.96846091e-02,
         6.05106732e-02,   6.32296312e-03,  -2.62722565e-01,
         8.30559199e-02])

- note:影响因素还有截距，10个变量共同影响了直线的斜率，每个影响的权重不同。

我自己理解系数表示线性函数的斜率，以上输出的数组中包含10个元素，分别代表这个模型下每个特征向量分类的决策边界倾斜率

- 3.使用决策树/SVM/KNN...等sklearn分类算法进行分类，尝试了解参数含义，调整不同的参数。

In [13]:
'''不怎么理解参数的含义，是指各个类里面的参数呢，还是最后生成的模型的参数？
'''
from sklearn.tree import DecisionTreeClassifier
# tree = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
tree = DecisionTreeClassifier()
# """参数
#     criterion ：特征选择准则gini/entropy
#     max_depth：树的最大深度，None-尽量下分
#     min_samples_split：分裂内部节点，所需要的最小样本树
#     min_samples_leaf：叶子节点所需要的最小样本数
#     max_features: 寻找最优分割点时的最大特征数
#     max_leaf_nodes：优先增长到最大叶子节点数
#     min_impurity_decrease：如果这种分离导致杂质的减少大于或等于这个值，则节点将被拆分。
# """
tree.fit(X_train,y_train)#


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [66]:
from sklearn.svm import SVC
svm = SVC(random_state=0, gamma=0.2, C=1.0)
# """参数
# ---
#     C：误差项的惩罚参数C
#     gamma: 核相关系数。浮点数，If gamma is ‘auto’ then 1/n_features will be used instead.
# """
svm.fit(X_train,y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.2, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [67]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

- 4.在测试集上进行预测，计算准确度

In [9]:
y_lr_pred_class=LR.predict(X_test)
LR.score(X_test,y_test)

0.93321061512501913

In [14]:
tree.predict(X_test)
tree.score(X_test,y_test)

0.89394078846448843

In [71]:
svm.predict(X_test)
svm.score(X_test,y_test)

0.9328424605000767

In [72]:
knn.predict(X_test)
knn.scoreoreoreore(X_test,y_test)

0.9315232397606995

- 5.查看sklearn的官方说明，了解混淆矩阵等评估标准，并对此例进行评估。

In [15]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_lr_pred_class))

[[30389    18]
 [ 2159    29]]


In [16]:
# 真阳性（True Positive，TP）：指被分类器正确分类的正例数据
# 真阴性（True Negative，TN）：指被分类器正确分类的负例数据
# 假阳性（False Positive，FP）：被错误地标记为正例数据的负例数据
# 假阴性（False Negative，FN）：被错误地标记为负例数据的正例数据
confusion = metrics.confusion_matrix(y_test, y_lr_pred_class)
TP = confusion[1, 1]
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]
print("分类器正确分类的正例数据:", TP)
print("分类器正确分类的负例数据:", TN)
print("被错误地标记为正例数据的负例数据:", FP)
print("被错误地标记为负例数据的正例数据:", FN)
# print("分类准确率:",(TP+TN) / float(TP+TN+FN+FP))
print("分类准确率:",metrics.accuracy_score(y_test, y_lr_pred_class))

分类器正确分类的正例数据: 29
分类器正确分类的负例数据: 30389
被错误地标记为正例数据的负例数据: 18
被错误地标记为负例数据的正例数据: 2159
分类准确率: 0.933210615125


- 6.银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。   
比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”   
试试看把阈值设定为0.3，再看看这个时候的混淆矩阵等评估指标。

In [35]:
y_pred_prob=LR.predict_proba(X_test)[:,1]
y_pred_prob

array([ 0.07979306,  0.0727971 ,  0.03183313, ...,  0.14508883,
        0.05818366,  0.07477596])

In [38]:
y_pred_prob.reshape(1,-1)

array([[ 0.07979306,  0.0727971 ,  0.03183313, ...,  0.14508883,
         0.05818366,  0.07477596]])

In [29]:
y_lr_pred_class=LR.predict(X_test)
y_lr_pred_class

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
# predict diabetes if the predicted probability is greater than 0.3
from sklearn.preprocessing import binarize
from sklearn.preprocessing import Binarizer
y_pred_class = binarize(y_pred_prob.reshape(1,-1), 0.3)[0]
y_pred_class


array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [43]:
metrics.confusion_matrix(y_test,y_pred_class)
# [[30389    18]
#  [ 2159    29]]

array([[30369,    38],
       [ 2141,    47]], dtype=int64)

In [48]:
'''修改阈值之后，预测正样本正确的比例由原来的29上升到47，
正样本的准确率上升了，但是总体准确率下降了，可能是该模型对正样本预测比较差，对负样本预测比较好'''
print("没修改前分类准确率    :",metrics.accuracy_score(y_test, y_lr_pred_class))
print("修改阈值之后分类准确率:",metrics.accuracy_score(y_test, y_pred_class))

没修改前分类准确率    : 0.933210615125
修改阈值之后分类准确率: 0.933149256021


- 7.尝试对不同特征的重要度进行排序，通过特征选择的方式，对特征进行筛选。并重新建模，观察此时的模型准确率等评估指标。

In [68]:
# Xb
# Xb.shape
X.shape

(108648, 10)

In [113]:
X_array=np.array(X)#把dataframe转换为array，方面下面计算
X_array

array([[  0.76612661,  45.        ,   2.        , ...,   6.        ,
          0.        ,   2.        ],
       [  0.95715102,  40.        ,   0.        , ...,   0.        ,
          0.        ,   1.        ],
       [  0.65818014,  38.        ,   1.        , ...,   0.        ,
          0.        ,   0.        ],
       ..., 
       [  0.29974515,  44.        ,   0.        , ...,   1.        ,
          0.        ,   2.        ],
       [  0.        ,  30.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.85028295,  64.        ,   0.        , ...,   2.        ,
          0.        ,   0.        ]])

In [112]:
names=X.columns#获取特征名称
names

Index(['RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [83]:
names=X.columns
rf = RandomForestRegressor(n_estimators=20, max_depth=4)  
scores = []  
for i in range(X_array.shape[1]):
    score = cross_val_score(rf,X_array[:,i:i+1],y,scoring='r2',cv=ShuffleSplit(len(X_array),3,.3))  
    scores.append((round(np.mean(score), 3),names[i])) 
print ('特征重要度排序：',sorted(scores, reverse=True))

特征重要度排序： [(0.11799999999999999, 'NumberOfTimes90DaysLate'), (0.086999999999999994, 'RevolvingUtilizationOfUnsecuredLines'), (0.074999999999999997, 'NumberOfTime30-59DaysPastDueNotWorse'), (0.071999999999999995, 'NumberOfTime60-89DaysPastDueNotWorse'), (0.012, 'age'), (0.0089999999999999993, 'NumberOfOpenCreditLinesAndLoans'), (0.0060000000000000001, 'MonthlyIncome'), (0.0040000000000000001, 'DebtRatio'), (0.0030000000000000001, 'NumberRealEstateLoansOrLines'), (0.002, 'NumberOfDependents')]


In [111]:
'''根据以上排序去掉后面5列scores小于0.01的特征，然后重新建模试试看'''
X_new=X.drop(['NumberOfDependents','NumberRealEstateLoansOrLines','DebtRatio','MonthlyIncome','NumberOfOpenCreditLinesAndLoans'],axis=1)
X_new.shape

(108648, 5)

In [110]:
'''重新建模'''
X_new_train, X_new_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=42)
LR_new = LogisticRegression()
LR_new.fit(X_new_train,y_train)
new_y_lr_pred_class=LR_new.predict(X_new_test)
print('在建模之前的评分:',LR.score(X_test,y_test))
print('重新建模后的评分:',LR_new.score(X_new_test,y_test))


在建模之前的评分: 0.933210615125
重新建模后的评分: 0.934008283479


### 本阶段课程意见反馈题(5分送分项，非必答)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


In [ ]:
这第六周一下子好多知识点，各种模型,算法，之前都没怎么接触过。之前看的预习视频看一点，没看完，一下子这么多
模型、算法要理解，感觉难度很大。作业题目基本不会，考试题目都是各种上网参考写出来的。已经买了那本著名的西瓜书，
会好好把理论啃一啃的。

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

In [ ]:
这周的课程挺难的，不过老师设计的考试的题目挺好的，本来完全不理解各种模型、算法，通过考试题目做一做，至少知道代码是怎么实现的。

<hr>
<center><h1>####答卷结束####</h1></center>