## 七月在线机器学习实训营三期第六周(机器学习)考试
#### 考试说明:
- 起止时间：请同学在2018年3月16日至3月18日期间完成，最晚提交时间本周日（3月18日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam6后，进行作答。例如wangwei-exam6
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/4/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>彭志雄</u>  
- 批改人： David
- 最终得分: 100

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共4题，每题5分，共计20分)

#### 1. 请写出你了解的机器学习特征工程操作，以及它的意义（面试题）

   #### （1）数据预处理
   - 处理缺失值
     - 缺失值较多的特征处理：一般如果某特征的缺失量过大，我们会直接将该特征舍弃掉，否则可能反倒会带入较大的noise，对结果造成不良影响。
     - 缺失值较少的特征处理：用规则或模型将缺失数据补全，这种做法的缺点是可能会引入噪声。  
     ①把NaN直接作为一个特征，假设用0表示；  
     ②用均值填充；有时候还有可能遇到这样一种情况，那就是训练集train中有缺失值，而test中无缺失值 ，这时候最适合的处理方式应该是对缺失值取    条件均值或条件中值，即即根据该用户的label值类别，取所有该label下用户该属性的均值或中值。  
     ③用前后数据进行填充；  
     ④用插值法填充；插值法就是通过两点(x0,y0),(x1,y1)估计中间点的值（pd.interpolate()）  
     - 忽略：有一些模型，如随机森林，自身能够处理数据缺失的情况，在这种情况下不需要对缺失数据做任何的处理，这种做法的缺点是在模型的选择上有局限。
   - 处理脏数据
     - 不可信的样本直接丢掉，比如一个人身高3米的人、一个人一个月买了10万元的发卡。 
   - 数据采样
     - 若数据的正负样本不均衡，则要进行数据采样。采样的方法有随机采样和分层抽样。但是随机采样会有隐患，因为可能某次随机采样得到的数据很不均匀，更多的是根据特征采用分层抽样。
     
#### （2）特征处理
  - 数值型
    - 幅度调整/归一化：python中会有一些函数比如preprocessing.MinMaxScaler()，可以消除样本不同属性具有不同量级时的影响：  
    ①数量级的差异将导致量级较大的属性占据主导地位，譬如SVM，可能会出现数值过大导致c,g取值超过寻优范围；  
    ②数量级的差异将导致迭代收敛速度减慢甚至不收敛，例如LR和神经网络。
    - 统计值：包括max, min, mean, std等。python中用pandas库序列化数据后，可以得到数据的统计值。 
    - 离散化：把连续值转成非线性数据。例如电商会有各种连续的价格表，从0.03到100元，假如以一元钱的间距分割成99个区间，用99维的向量代表每一个价格所处的区间，1.2元和1.6元的向量都是 [0,1,0,…,0]。pd.cut() 可以直接把数据分成若干段。
    - 柱状分布：离散化后统计每个区间的个数做柱状图。
  - 类别型
  类别型一般是文本信息，比如颜色是红色、黄色还是蓝色，我们存储数据的时候就需要先处理数据。处理方法有： 
    - one-hot编码，编码后得到哑变量。能够处理非数值属性，避免引入大小关系；在一定程度上扩充了特征；编码后的属性是稀疏的，存在大量的零元分量。。 
    - Hash编码成词向量
    - Histogram映射：把每一列的特征拿出来，根据target内容做统计，把target中的每个内容对应的百分比填到对应的向量的位置。优点是把两个特征联系起来。 
  - 时间型
    - 时间型特征的用处特别大，既可以看做连续值（持续时间、间隔时间），也可以看做离散值（星期几、几月份）。数据挖掘中经常会用时间作为重要特征，比如电商可以分析节假日和购物的关系，一天中用户喜好的购物时间等。
  - 文本型
    - 词袋：文本数据预处理后，去掉停用词，剩下的词组成的list，在词库中的映射稀疏向量。Python中用CountVectorizer处理词袋。
    - 把词袋中的词扩充到n-gram：n-gram代表n个词的组合。比如“我喜欢你”、“你喜欢我”这两句话如果用词袋表示的话，分词后包含相同的三个词，组成一样的向量：“我 喜欢 你”。显然两句话不是同一个意思，用n-gram可以解决这个问题。如果用2-gram，那么“我喜欢你”的向量中会加上“我喜欢”和“喜欢你”，“你喜欢我”的向量中会加上“你喜欢”和“喜欢我”。这样就区分开来了。
    - 使用TF-IDF特征：TF-IDF是一种统计方法，用以评估一字词对于一个文件集或一个语料库中的其中一份文件的重要程度。字词的重要性随着它在文件中出现的次数成正比增加，但同时会随着它在语料库中出现的频率成反比下降。TF(t) = (词t在当前文中出现次数) / (t在全部文档中出现次数)，IDF(t) = ln(总文档数/ 含t的文档数)，TF-IDF权重 = TF(t) * IDF(t)。自然语言处理中经常会用到。
  - 统计型
    - 历届的Kaggle/天池比赛， 天猫/京东排序和推荐业务线里模型用到的特征。统计的内容包括加减平均、分位线、次序型、比例类等。

#### （3）特征选择  
特征选择，就是从多个特征中，挑选出一些对结果预测最有用的特征。因为原始的特征中可能会有冗余和噪声。  
进行特征选择的意义有：①减轻维数灾难问题；②降低学习任务的难度。    
常见的特征选择方法分为如下三类：    
   - 过滤式（filter）方法评估单个特征和结果值之间的相关程度，主要采用Pearson相关系数，排序留下Top相关的特征部分。缺点是只评估了单个特征对结果的影响，没有考虑到特征之间的关联作用， 可能把有用的关联特征误踢掉。因此工业界使用比较少。
   - 包裹式（wrapper）的经典算法是递归特征消除法（RFE）：使用一个基模型在全量特征上进行多轮训练，每轮训练后，消除若干权值系数低的特征，再基于新的特征集进行下一轮训练。其优点是直接针对特定学习器进行优化，因此通常包裹式特征选择比过滤式特征选择更好，缺点是由于特征选择过程需要多次训练学习器，故计算开销要比过滤式特征选择要大得多。
   - 嵌入式（embedding）方法的主要思想是在模型既定的情况下学习出对提高模型准确性最好的属性。
     - 基于惩罚项的特征选择法：使用带惩罚项的基模型，除了筛选出特征外，同时也进行了降维。实际上，L1惩罚项降维的原理在于选择多个对目标值具有同等相关性的特征中的一个，所以没选到的特征不代表不重要。故，可结合L2惩罚项来优化。
     - 基于树模型的特征选择法：树模型中GBDT也可用来作为基模型进行特征选择。

#### 2.请写出上述特征工程操作的sklearn或者pandas实现方式


In [11]:
import pandas as pd
df_train = pd.read_csv('./train.csv')
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [12]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [21]:
#缺失值填充，使用pandas的fillna函数
print(df_train['Age'].fillna(value=df_train['Age'].mean()).head(20))

## 使用sklearn当中的Imputer
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean', axis=0)
age = imp.fit_transform(df_train[['Age']].values)
age[:20]#取出前20项数据

0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
5     29.699118
6     54.000000
7      2.000000
8     27.000000
9     14.000000
10     4.000000
11    58.000000
12    20.000000
13    39.000000
14    14.000000
15    55.000000
16     2.000000
17    29.699118
18    31.000000
19    29.699118
Name: Age, dtype: float64


array([[ 22.        ],
       [ 38.        ],
       [ 26.        ],
       [ 35.        ],
       [ 35.        ],
       [ 29.69911765],
       [ 54.        ],
       [  2.        ],
       [ 27.        ],
       [ 14.        ],
       [  4.        ],
       [ 58.        ],
       [ 20.        ],
       [ 39.        ],
       [ 14.        ],
       [ 55.        ],
       [  2.        ],
       [ 29.69911765],
       [ 31.        ],
       [ 29.69911765]])

#### 数值型

- （1）幅度缩放

In [23]:
# 取log缩放
import numpy as np
log_age = df_train['Age'].apply(np.log)
log_age.head()

0    3.091042
1    3.637586
2    3.258097
3    3.555348
4    3.555348
Name: Age, dtype: float64

In [31]:
# 最大最小值缩放
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
fare_trans = mm_scaler.fit_transform(df_train[['Fare']])
print(fare_trans[:20])
#标准化
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
fare_std_trans = std_scaler.fit_transform(df_train[['Fare']])
fare_std_trans[:20]

[[ 0.01415106]
 [ 0.13913574]
 [ 0.01546857]
 [ 0.1036443 ]
 [ 0.01571255]
 [ 0.0165095 ]
 [ 0.10122886]
 [ 0.04113566]
 [ 0.02173075]
 [ 0.05869429]
 [ 0.03259623]
 [ 0.05182215]
 [ 0.01571255]
 [ 0.06104473]
 [ 0.01533038]
 [ 0.03122992]
 [ 0.05684821]
 [ 0.02537431]
 [ 0.03513366]
 [ 0.01410226]]


array([[-0.50244517],
       [ 0.78684529],
       [-0.48885426],
       [ 0.42073024],
       [-0.48633742],
       [-0.47811643],
       [ 0.39581356],
       [-0.22408312],
       [-0.42425614],
       [-0.0429555 ],
       [-0.31217238],
       [-0.11384571],
       [-0.48633742],
       [-0.01870931],
       [-0.49027979],
       [-0.32626666],
       [-0.06199889],
       [-0.38667072],
       [-0.28599728],
       [-0.50294854]])

- （2）统计结果作为特征

In [32]:
# max min
print(df_train["Age"].max())
print(df_train["Age"].min())

80.0
0.42


In [33]:
#第1四分位数 (Q1)
age_quarter_1 = df_train['Age'].quantile(0.25)
age_quarter_1

20.125

In [34]:
#第3四分位数 (Q3)
age_quarter_3 = df_train['Age'].quantile(0.75)
age_quarter_3

38.0

- （3）四则运算

In [35]:
df_train.loc[:,'family_size'] = df_train['SibSp'] + df_train['Parch'] + 1
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  family_size  
0      0         A/5 21171   7.2500   NaN        S            2  
1      0          PC 17599  71.2833   C85        C            2  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            2  
4      0            373450   8.0500   NaN        S            1

- （4）构造高次特征和交叉特征

In [38]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
poly_fea = poly.fit_transform(df_train[['SibSp', 'Fare']])
poly_fea[:5,:]

array([[  1.00000000e+00,   1.00000000e+00,   7.25000000e+00,
          1.00000000e+00,   7.25000000e+00,   5.25625000e+01],
       [  1.00000000e+00,   1.00000000e+00,   7.12833000e+01,
          1.00000000e+00,   7.12833000e+01,   5.08130886e+03],
       [  1.00000000e+00,   0.00000000e+00,   7.92500000e+00,
          0.00000000e+00,   0.00000000e+00,   6.28056250e+01],
       [  1.00000000e+00,   1.00000000e+00,   5.31000000e+01,
          1.00000000e+00,   5.31000000e+01,   2.81961000e+03],
       [  1.00000000e+00,   0.00000000e+00,   8.05000000e+00,
          0.00000000e+00,   0.00000000e+00,   6.48025000e+01]])

- （5）离散化/分箱/分桶

In [44]:
#pandas cut 
df_train.loc[:,'fare_cut'] = pd.cut(df_train['Fare'],5)
df_train.fare_cut.value_counts()

(-0.512, 102.466]     838
(102.466, 204.932]     33
(204.932, 307.398]     17
(409.863, 512.329]      3
(307.398, 409.863]      0
Name: fare_cut, dtype: int64

In [41]:
#pandas qcut
df_train.loc[:,'fare_qcut'] = pd.qcut(df_train['Fare'],5)
df_train.fare_qcut.value_counts()

(7.854, 10.5]        184
(21.679, 39.688]     180
(-0.001, 7.854]      179
(39.688, 512.329]    176
(10.5, 21.679]       172
Name: fare_qcut, dtype: int64

- （6）独热向量编码

In [45]:
df_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  family_size           fare_cut  \
0      0  A/5 21171   7.2500   NaN        S            2  (-0.512, 102.466]   
1      0   PC 17599  71.2833   C85        C            2  (-0.512, 102.466]   

           fare_qcut  
0    (-0.001, 7.854]  
1  (39.688, 512.329]

In [46]:
embarked_oht = pd.get_dummies(df_train[['Embarked']])
embarked_oht.head()

Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

- （7）时间型

In [47]:
df_time = pd.DataFrame({'date':['20180314', '20180311', '20180227','20180114'],'cnt':[21,25,16,19]})
df_time

cnt      date
0   21  20180314
1   25  20180311
2   16  20180227
3   19  20180114

In [49]:
df_time.loc[:,'dt'] = pd.to_datetime(df_time['date'])
df_time.head()

cnt      date         dt
0   21  20180314 2018-03-14
1   25  20180311 2018-03-11
2   16  20180227 2018-02-27
3   19  20180114 2018-01-14

In [50]:
df_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
cnt     4 non-null int64
date    4 non-null object
dt      4 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 176.0+ bytes


#### 特征选择

- 过滤式/Filter

In [51]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [52]:
X_new = SelectKBest(k=2).fit_transform(X,y)
print(X_new.shape)
X_new[:6,:]

(150, 2)


array([[ 1.4,  0.2],
       [ 1.4,  0.2],
       [ 1.3,  0.2],
       [ 1.5,  0.2],
       [ 1.4,  0.2],
       [ 1.7,  0.4]])

- 包裹式/wrapper

In [53]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rfe = RFE(estimator=rf, n_features_to_select=2)
X_rfe = rfe.fit_transform(X,y)
X_rfe[:6,:]

array([[ 1.4,  0.2],
       [ 1.4,  0.2],
       [ 1.3,  0.2],
       [ 1.5,  0.2],
       [ 1.4,  0.2],
       [ 1.7,  0.4]])

- 嵌入式/Embedded

In [54]:
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
lsvc = LinearSVC(C=0.01, penalty='l1', dual=False).fit(X,y)
model = SelectFromModel(lsvc, prefit=True)
X_embedd = model.transform(X)
X_embedd[:6,:]

array([[ 5.1,  3.5,  1.4],
       [ 4.9,  3. ,  1.4],
       [ 4.7,  3.2,  1.3],
       [ 4.6,  3.1,  1.5],
       [ 5. ,  3.6,  1.4],
       [ 5.4,  3.9,  1.7]])

#### 3.模型评估中的留一法，留出法，交叉验证分别是什么操作？

- 留出法：直接将数据集D划分成两个互斥的集合，其中一个集合作为训练集S，另一个作为测试集T，在S上训练出模型后，用T来评估其测试误差，作为对泛化误差的估计。
- 留一法：假设有N个样本，将每一个样本作为测试样本，其它N-1个样本作为训练样本。这样得到N个分类器，N个测试结果。用这N个结果的平均值来衡量模型的性能。
- 交叉验证：将全部训练集 S分成 k个不相交的子集，假设 S中的训练样例个数为 m，那么每一个子 集有 m/k 个训练样例，，相应的子集称作 {s1,s2,……,sk}；每次从分好的子集中里面，拿出一个作为测试集，其它k-1个作为训练集；根据训练训练出模型或者假设函数，把这个模型放到测试集上，得到分类率；计算k次求得的分类率的平均值，作为该模型或者假设函数的真实分类率。

#### 4.如何理解模型的过拟合与欠拟合，以及如何解决？（面试题）

- 欠拟合  
欠拟合就是模型没有很好地捕捉到数据特征，不能够很好地拟合数据。  
解决方法：  
  - 添加其他特征项，有时候我们模型出现欠拟合的时候是因为特征项不够导致的，可以添加其他特征项来很好地解决。例如，“组合”、“泛化”、“相关性”三类特征是特征添加的重要手段，无论在什么场景，都可以照葫芦画瓢，总会得到意想不到的效果。除上面的特征之外，“上下文特征”、“平台特征”等等，都可以作为特征添加的首选项。
  - 添加多项式特征，这个在机器学习算法里面用的很普遍，例如将线性模型通过添加二次项或者三次项使模型泛化能力更强。例如上面的图片的例子。
  - 减少正则化参数，正则化的目的是用来防止过拟合的，但是现在模型出现了欠拟合，则需要减少正则化参数。  
  
  
- 过拟合  
过拟合就是模型把数据学习的太彻底，以至于把噪声数据的特征也学习到了，这样就会导致在后期测试的时候不能够很好地识别数据，即不能正确的分类，模型泛化能力太差。  
解决方法：  
  - 重新清洗数据，导致过拟合的一个原因也有可能是数据不纯导致的，如果出现了过拟合就需要我们重新清洗数据。
  - 增大数据的训练量，还有一个原因就是我们用于训练的数据量太小导致的，训练数据占总数据的比例过小。
  - 采用正则化方法。正则化方法包括L0正则、L1正则和L2正则，而正则一般是在目标函数之后加上对于的范数。但是在机器学习中一般使用L2正则。
  - 采用dropout方法。这个方法在神经网络里面很常用。dropout方法是ImageNet中提出的一种方法，通俗一点讲就是dropout方法在训练的时候让神经元以一定的概率不工作。

## 操作题(共1题，共计80分)

- note: 80

### 信用卡欺诈项目(共7项，前5项每题10分，6，7题每题15分)

- 前期数据导入,预览及处理(此部分勿修改，涉及的数据文件无需复制移动)

In [76]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [77]:
data.shape

(112915, 11)

In [78]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [79]:
data.dropna(inplace=True)
data.shapey = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

In [80]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)
y.mean()

0.06742876076872101

- 1.把数据切分成训练集和测试集

In [81]:
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version
if Version(sklearn_version) < '0.18':
    from sklearn.cross_validation import train_test_split
else:
    from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [82]:
X_train.shape

(76053, 10)

In [83]:
X_test.shape

(32595, 10)

In [84]:
y_train.shape

(76053,)

In [85]:
y_test.shape

(32595,)

- 2.使用logistic regression建模，并且输出一下系数，分析重要度。   

In [95]:
#先对数值型特征进行标准化
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train_std=std.fit_transform(X_train)
X_test_std=std.transform(X_test)

In [96]:
#建模
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(penalty='l1',C=10, random_state=0)
LR.fit(X_train_std, y_train)
LR

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [97]:
print('逻辑回归训练集准确度：%f'%LR.score(X_train_std,y_train))

逻辑回归训练集准确度：0.933126


In [98]:
import numpy as np
labels=data.columns[1:]
coefs=LR.coef_      #coef_存放回归系数，intercept_存放截距
indexs=np.argsort(coefs[0])[::-1]
for i in range(X_train.shape[1]):
    print ('%d  %s  %f'%(i,labels[indexs[i]],coefs[0,indexs[i]]))

0  NumberOfTime30-59DaysPastDueNotWorse  1.728235
1  NumberOfTimes90DaysLate  1.688007
2  DebtRatio  0.312083
3  NumberOfDependents  0.116360
4  RevolvingUtilizationOfUnsecuredLines  -0.014233
5  NumberOfOpenCreditLinesAndLoans  -0.091907
6  MonthlyIncome  -0.114985
7  NumberRealEstateLoansOrLines  -0.196426
8  age  -0.364293
9  NumberOfTime60-89DaysPastDueNotWorse  -3.246326


重要度分析：系数绝对值越大，则对应特征的重要度越大，重要度排名前三的特征都是逾期还款但不糟糕的次数，可见人的信用情况对于债务违约的概率具有至关重要的影响。

- 3.使用决策树/SVM/KNN...等sklearn分类算法进行分类，尝试了解参数含义，调整不同的参数。

In [99]:
#决策树
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(max_depth=10, random_state=0)
DT.fit(X_train_std, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [100]:
print ('决策树训练集准确度：%f'%DT.score(X_train_std,y_train))

决策树训练集准确度：0.946458


In [101]:
#SVM
from sklearn.svm import SVC
SVM = SVC(degree=4,max_iter=5000)
SVM.fit(X_train_std, y_train)

C:\Users\pengzx\Anaconda3\lib\site-packages\sklearn\svm\base.py:218: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='rbf',
  max_iter=5000, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [102]:
print ('SVM训练集准确度：%f'%SVM.score(X_train_std,y_train))

SVM训练集准确度：0.936018


In [103]:
#knn
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=4)
KNN.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [104]:
print ('KNN训练集准确度：%f'%KNN.score(X_train_std,y_train))

KNN训练集准确度：0.932218


- 4.在测试集上进行预测，计算准确度

In [105]:
#logistic regression
y_pred_lr=LR.predict(X_test)
print('LR错误分类数: %d' % (y_test != y_pred_lr).sum())
print('LR测试集准确度：%f'%LR.score(X_test_std,y_test))

LR错误分类数: 2171
LR测试集准确度：0.933855


In [106]:
#决策树
y_pred_tree=DT.predict(X_test)
print('决策树错误分类数: %d' % (y_test != y_pred_tree).sum())
print('决策树测试集准确度：%f'%DT.score(X_test_std,y_test))

决策树错误分类数: 2186
决策树测试集准确度：0.931922


In [107]:
#SVM
y_pred_svm=SVM.predict(X_test)
print('错误分类数: %d' % (y_test != y_pred_svm).sum())
print('测试集准确度：%f'%SVM.score(X_test_std,y_test))

错误分类数: 2171
测试集准确度：0.936432


In [108]:
#KNN
y_pred_knn=KNN.predict(X_test)
print('KNN错误分类数: %d' % (y_test != y_pred_knn).sum())
print('KNN测试集准确度：%f'%KNN.score(X_test,y_test))

KNN错误分类数: 2195
KNN测试集准确度：0.932658


- 5.查看sklearn的官方说明，了解混淆矩阵等评估标准，并对此例进行评估。

#### 评估标准：
  - AccuracyRate(准确率): (TP+TN)/(TP+TN+FN+FP)
  - ErrorRate(误分率): (FN+FP)/(TP+TN+FN+FP)
  - Recall(召回率，查全率,击中概率): TP/(TP+FN), 在所有真正的正样本中有多少被识别为正样本了
  - Precision(查准率):TP/(TP+FP),在所有识别成正样本中有多少是真正的正样本
  - FAR(FalseAcceptance Rate)或FPR(False Positive Rate)：FP/(FP+TN)， 错误接收率，误报率，在所有标记为负样本中有多少被识别为正样本了
  - FRR(FalseRejection Rate): FN/(TP+FN)，错误拒绝率，拒真率，在所有标记为正样本中有多少被识别为负样本了，它等于1-Recall
  - ROC曲线（receiver operatingcharacteristic curve）：  
  ①横轴是FAR,纵轴是Recall；  
  ②每个阈值的识别结果对应一个点(FPR，TPR),当阈值最大时，所有样本都被识别成负样本，对应于右上角的点(0,0)，当阈值最小时，所有样本都被识别成正样本，对应于右上角的点(1,1)，随着阈值从最大变化到最小，TP和FP都逐渐增大；  
  ③可以使用ROC曲线下方的面积AUC（AreaUnder roc Curve）值来度量算法好坏：如果模型是完美的，那么它的AUG = 1，如果模型是个简单的随机猜测模型，那么它的AUG = 0.5，如果一个模型好于另一个，则它的曲线下方面积相对较大；  
  ④一个好的分类模型应尽可能位于图像的左上角，而一个随机猜测模型应位于连接点（TPR=0,FPR=0）和（TPR=1,FPR=1）的主对角线上；  
  ⑤ERR（Equal Error Rate,相等错误率）：FAR和FRR是同一个算法系统的两个参数，把它放在同一个坐标中。FAR是随阈值增大而减小的，FRR是随阈值增大而增大的。因此它们一定有交点。这个点是在某个阈值下的FAR与FRR等值的点。习惯上用这一点的值来衡量算法的综合性能。对于一个更优的指纹算法，希望在相同阈值情况下，FAR和FRR都越小越好。  

In [109]:
#对LR模型评估
from sklearn.metrics import confusion_matrix
confusion_lr=confusion_matrix(y_test, y_pred_lr)
confusion_lr

array([[30424,     0],
       [ 2171,     0]], dtype=int64)

In [110]:
#对决策树模型评估
confusion_tree=confusion_matrix(y_test, y_pred_tree)
confusion_tree

array([[30259,   165],
       [ 2021,   150]], dtype=int64)

In [111]:
#对SVM模型评估
confusion_svm=confusion_matrix(y_test, y_pred_svm)
confusion_svm

array([[30424,     0],
       [ 2171,     0]], dtype=int64)

In [112]:
#对KNN模型评估
confusion_knn=confusion_matrix(y_test, y_pred_knn)
confusion_knn

array([[30383,    41],
       [ 2154,    17]], dtype=int64)

- 6.银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。   
比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”   
试试看把阈值设定为0.3，再看看这个时候的混淆矩阵等评估指标。

In [113]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='l2',C=10, random_state=0,class_weight={1:0.3,0:0.7})#由于误分类，故适当提高负样本的权重
lr.fit(X_train, y_train)
lr

LogisticRegression(C=10, class_weight={1: 0.3, 0: 0.7}, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=0,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [114]:
y_pred_lr=lr.predict(X_test)
print('错误分类数: %d' % (y_test != y_pred_lr).sum())
print('测试集准确度：%f'%lr.score(X_test,y_test))

错误分类数: 2169
测试集准确度：0.933456


In [115]:
confusion_lr=confusion_matrix(y_test, y_pred_lr)
confusion_lr

array([[30410,    14],
       [ 2155,    16]], dtype=int64)

可见召回率由100%下降到99.954%，查准率由93.339%上升到93.382%

- 7.尝试对不同特征的重要度进行排序，通过特征选择的方式，对特征进行筛选。并重新建模，观察此时的模型准确率等评估指标。

In [116]:
#用随机森林模型对特征进行筛选
from sklearn.ensemble import RandomForestClassifier
feat_labels = data.columns[1:]
forest=RandomForestClassifier(n_estimators=1000,random_state=0,n_jobs=-1)
forest.fit(X_train,y_train)
importances=forest.feature_importances_

In [117]:
import numpy as np
labels=data.columns[1:]
indexs=np.argsort(importances)[::-1]
for i in range(X_train.shape[1]):
    print('%d %s %f'%(i,labels[indexs[i]],importances[indexs[i]]))

0 RevolvingUtilizationOfUnsecuredLines 0.188899
1 DebtRatio 0.172926
2 MonthlyIncome 0.165889
3 age 0.122358
4 NumberOfOpenCreditLinesAndLoans 0.089148
5 NumberOfTimes90DaysLate 0.087252
6 NumberOfTime30-59DaysPastDueNotWorse 0.051195
7 NumberOfDependents 0.046049
8 NumberOfTime60-89DaysPastDueNotWorse 0.044431
9 NumberRealEstateLoansOrLines 0.031852


In [118]:
#选取按重要度排序的前4个特征，建立逻辑回归模型（很奇怪为啥LR与forest模型训练出来的特征重要度排序相差这么大，不知是树太少还是LR不行）
X_train_4=X_train[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age']]
X_test_4=X_test[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age']]
#对特征进行标准化
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train_std=std.fit_transform(X_train_4)
X_test_std=std.transform(X_test_4)

In [119]:
#重新建模
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='l1',C=10.0, random_state=0)
lr.fit(X_train_std, y_train)
lr

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [120]:
print('训练集准确度：%f'%lr.score(X_train_std,y_train))

训练集准确度：0.932218


In [121]:
y_pred_lr=lr.predict(X_test_std)
print('错误分类数: %d' % (y_test != y_pred_lr).sum())
print ('测试集准确度：%f'%lr.score(X_test_std,y_test))

错误分类数: 2171
测试集准确度：0.933395


In [122]:
confusion_lr=confusion_matrix(y_test, y_pred_lr)
confusion_lr

array([[30424,     0],
       [ 2171,     0]], dtype=int64)

通过对比可看出，特征筛选前与筛选后，模型各项评估指标没有明显变化，但是降低了特征数量，加快了训练时间

### 本阶段课程意见反馈题(5分送分项，非必答)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


    对特征工程的基本流程有一定的认识，对各种模型和学习算法有一定的了解，对sklearn中一些常见API的参数有一些了解；完成作业用时过长

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

    这周课程涉及的知识点较多，还得多理一理思路

<hr>
<center><h1>####答卷结束####</h1></center>