## 七月在线机器学习实训营三期第七周(机器学习-模型调优与融合)考试
#### 考试说明:
- 起止时间：请同学在2018年3月23日至3月25日期间完成，最晚提交时间本周日（3月25日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam7后，进行作答。例如wangwei-exam7
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/7/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>_司玉辰____</u>  
- 批改人： David
- 最终得分:90

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共6题，1，2题每题5分，后4题每题10分，共计50分)

- note: 50

#### 1. 机器学习任务中，通常会将给定数据切分为训练集，验证集，测试集，请回答这三类数据集各自的用途。

训练集：用于预估模型，学习样本数据集，通过匹配一些参数来建立一个分类器。建立一种分类的方式，主要是用来训练模型的。
验证集：确定网络结构或者控制模型复杂程度的参数。对学习出来的模型，调整分类器的参数，如在神经网络中选择隐藏单元数。验证集还用来确定网络结构或者控制模型复杂程度的参数。
测试集：检验最终选择最优的模型的性能如何。主要是测试训练好的模型的分辨能力

#### 2.如何将数据转换成xgboost内置用法的libsvm数据格式，以及该格式数据是如何解读的?

XGBoost可以加载libsvm格式的文本数据，加载的数据格式可以为Numpy的二维数组和XGBoost的二进制的缓存文件。加载的数据存储在对象DMatrix中。
加载libsvm格式的数据和二进制的缓存文件时可以使用如下方式
dtrain = xgb.DMatrix('train.svm.txt')
dtest = xgb.DMatrix('test.svm.buffer')
Label 1:value 2:value
Label：是类别的标识
Value：就是要训练的数据，数据之间用空格隔开
这样做可以减少内存的使用，并提高做矩阵内积时的运算速度。

#### 3. 对于自动特征选择，通常有哪三类方法？试写出每类方式的思想，以及在sklearn中的代码实现（面试题）

Filter方法：

主要思想是：对每一维的特征进行“打分”，即给每一维的特征赋予权重，这样的权重就代表着该维特征的重要性，然后依据权重进行排序。主要的方法是：Chi-squared test(卡方检验)，information gain(信息增益)，correlation coefficient scores(相关系数)

Wrapper方法：

其主要思想是：将子集的选择看作是一个搜索寻优问题，对组合进行评价，再与其他的组合进行比较。这样就将子集的选择看作是一个优化问题，这里有很多的优化算法可以解决，齐次是一些启发的优化算法，如GA，PSO，DE，ABC等。主要方法有：recursive feature elimination algorithm(递归特征消除算法)

Embedded方法：

其主要思想是：在模型既定的情况下学习出对提高模型准确性最好的属性。其实是讲在确定模型的过程中，挑选出那些对模型的训练有重要意义的属性。主要方法有：正则化，岭回归就是在基本线性回归的过程中加入了正则项。

In [1]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
iris = load_iris()
X, y = iris.data, iris.target
skb = SelectKBest(k=2).fit_transform(X,y)

In [2]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rfe = RFE(estimator=rf, n_features_to_select=3)
rfe.fit_transform(X,y)

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [4]:
from sklearn.feature_selection import SelectFromModel 
from sklearn.svm import LinearSVC 
svc = LinearSVC(C=0.01, penalty='l1', dual=False).fit(X,y)
model = SelectFromModel(svc, prefit=True) 
model.transform(X)

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.1, 1.5],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3

#### 4.网格搜索交叉验证的作用是什么，并简述网格搜索交叉验证是如何运行的？ 

网格搜索作用程序自动的帮你使用穷举法来将所用的参数都运行一遍，以便于选择最好的参数；
交叉验证：将训练集划分为训练集和验证集，也是便于验证选取模型参数的。


In [19]:
#!/usr/bin/python
import numpy as np
import xgboost as xgb
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=0)
### 载入数据用于训练
dtrain = xgb.DMatrix(X_train, label=y_train)
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'multi:softmax','num_class':3}
num_round = 2

print ('running cross validation')

xgb.cv(param, dtrain, num_round,  seed = 10)

running cross validation


test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.062115         0.032444           0.031171          0.012486
1          0.044097         0.044636           0.013394          0.010887

#### 5.工业界上模型整合有三大类方式？试简述每类方式其思想？（面试题）

1、群众的力量是伟大的，集体智慧是惊人的
voting 投票器
Bagging ：用一个算法不用全部数据集，每次取一个子集训练一个模型；用不同算法，对结果做投票或平均
随机森林：取部分子集和部分特征做训练，训练出不同的树
2、站在巨人的肩膀上，能看的更远
模型stacking：用多种predictor结果作为特征训练
blending
3、一万小时定律
Adaboost：重复迭代和训练，每次分配给错误的样本更高的权重，用简单的分类器叠加
Gradient Boosting Tree

#### 6.  我们可以将xgboost的中众多参数分类为哪三类？请写出哪些参数可以用什么方式用来控制过拟合？

总共有3类参数：通用参数general parameters
集成(增强)参数booster parameters 
任务参数task parameters
控制过拟合：max_depth用于设置树的最大深度
lambda:L2权重的L2正则化项
alpha:L1权重的L1正则化项

## 实验题(共2题，每题25分，共计50分)

- note :40分

### 1. 使用XGBoost内置方式，导入iris数据完成分类问题（要求以不同参数设置xgboost运行并比对），最后给出实验总结

In [21]:
from sklearn.datasets import load_iris
import xgboost as xgb
from sklearn.model_selection import train_test_split

In [22]:
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
d_train = xgb.DMatrix(data=X_train, label=y_train)
d_test = xgb.DMatrix(data=X_test, label=y_test)

In [173]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

由于label的值为0,1,2，所以num_class设为3，三个不同种类

In [27]:
watch_list = [(d_test,'eval'), (d_train,'train')]
param = {'max_depth':3, 'eta':0.1, 'objective':'multi:softmax', 'num_class':3}
num_round = 10
bst = xgb.train(param, d_train, num_round, watch_list)

[0]	eval-merror:0.022222	train-merror:0.019048
[1]	eval-merror:0.022222	train-merror:0.019048
[2]	eval-merror:0.022222	train-merror:0.019048
[3]	eval-merror:0.022222	train-merror:0.019048
[4]	eval-merror:0.022222	train-merror:0.019048
[5]	eval-merror:0.022222	train-merror:0.019048
[6]	eval-merror:0.022222	train-merror:0.019048
[7]	eval-merror:0.022222	train-merror:0.019048
[8]	eval-merror:0.022222	train-merror:0.019048
[9]	eval-merror:0.022222	train-merror:0.019048


In [56]:
xgb.cv(param, d_train, num_round, nfold=5, seed = 150)

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.047619         0.042592           0.016667          0.005832
1          0.047619         0.042592           0.021429          0.004762
2          0.038095         0.035635           0.016667          0.005832
3          0.038095         0.035635           0.019048          0.009524
4          0.038095         0.035635           0.019048          0.009524
5          0.038095         0.035635           0.019048          0.009524
6          0.038095         0.035635           0.019048          0.009524
7          0.038095         0.035635           0.019048          0.009524
8          0.038095         0.035635           0.019048          0.009524
9          0.038095         0.035635           0.016667          0.005832

In [58]:
param = {'max_depth':3, 'eta':0.5, 'objective':'multi:softmax', 'num_class':3}
xgb.cv(param, d_train, num_round, nfold=5, seed = 150)

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.057143         0.055533           0.023810          0.007529
1          0.057143         0.055533           0.026191          0.008908
2          0.066667         0.048562           0.026191          0.008908
3          0.066667         0.048562           0.016667          0.009524
4          0.066667         0.048562           0.014286          0.008909
5          0.057143         0.035635           0.007143          0.005832
6          0.057143         0.035635           0.002381          0.004762
7          0.066667         0.038095           0.000000          0.000000
8          0.057143         0.035635           0.000000          0.000000
9          0.066667         0.038095           0.000000          0.000000

eta变为0.5后，产生了震荡过拟合，损失反而变大了

In [24]:
param = {'max_depth':3, 'eta':0.05, 'objective':'multi:softmax', 'num_class':3}
xgb.cv(param, d_train, num_round, nfold=5, seed = 150)

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.038095         0.055533           0.026191          0.008908
1          0.038095         0.055533           0.021429          0.008909
2          0.038095         0.055533           0.021429          0.008909
3          0.038095         0.055533           0.021429          0.008909
4          0.038095         0.055533           0.021429          0.008909
5          0.038095         0.055533           0.021429          0.008909
6          0.038095         0.055533           0.021429          0.008909
7          0.038095         0.055533           0.021429          0.008909
8          0.038095         0.055533           0.019048          0.009524
9          0.038095         0.055533           0.021429          0.008909

eta变为0.05后，收敛速度有所下降，但是模型能力却并没有提高，所以还是baseline的参数为最佳参数。


### 2. 使用XGBoost的sklearn接口，对KaggleCredit2数据完成信用卡欺诈项目的建模及分析（要求以不同参数设置xgboost运行并比对），最后给出实验总结

- KaggleCredit2数据文件 位于/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip，请勿复制或移动该文件

- note: 参数调整比较，及最后总结 呢？

1、导入库

In [2]:
import pickle
import xgboost as xgb
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.datasets import load_iris, load_digits, load_boston

In [3]:
import zipfile
with zipfile.ZipFile("/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip", "r") as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f,index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [3]:
data['SeriousDlqin2yrs'].value_counts()

0    105299
1      7616
Name: SeriousDlqin2yrs, dtype: int64

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112915 entries, 0 to 112914
Data columns (total 11 columns):
SeriousDlqin2yrs                        112915 non-null int64
RevolvingUtilizationOfUnsecuredLines    112915 non-null float64
age                                     108648 non-null float64
NumberOfTime30-59DaysPastDueNotWorse    112915 non-null float64
DebtRatio                               112915 non-null float64
MonthlyIncome                           112915 non-null float64
NumberOfOpenCreditLinesAndLoans         112915 non-null float64
NumberOfTimes90DaysLate                 112915 non-null float64
NumberRealEstateLoansOrLines            112915 non-null float64
NumberOfTime60-89DaysPastDueNotWorse    112915 non-null float64
NumberOfDependents                      108648 non-null float64
dtypes: float64(10), int64(1)
memory usage: 10.3 MB


In [35]:
data['age'].fillna(data['age'].median(), inplace=True) 

In [36]:
data['NumberOfDependents'].fillna(data['NumberOfDependents'].mean(),inplace=True)

In [4]:
#data.dropna(inplace=True)

In [5]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

In [6]:
X.shape

(108648, 10)

In [7]:
y.shape

(108648,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
param ={'learning_rate':[0.05, 0.1], 'n_estimators':[50,100], 'max_depth':[3,4]}
#     'subsample':[0.7,0.8], 'colsample_bytree':[0.7,0.8]}
xgb_model = xgb.XGBClassifier()
clf = GridSearchCV(xgb_model, param, cv=5)
clf.fit(X_train,y_train)

In [ ]:
print(clf.best_score_)
print(clf.best_params_)

In [ ]:
y_pred = clf.best_estimator_.predict(X_test)

In [ ]:
print('Accuracy:',accuracy_score(y_test, y_pred))
print('Confusion_matrix:\n',confusion_matrix(y_test, y_pred))

### 本阶段课程意见反馈题(非必答，不送分)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

<hr>
<center><h1>####答卷结束####</h1></center>