## 七月在线机器学习实训营三期第六周(机器学习)考试
#### 考试说明:
- 起止时间：请同学在2018年3月16日至3月18日期间完成，最晚提交时间本周日（3月18日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam6后，进行作答。例如wangwei-exam6
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/4/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>张少洋</u>  
- 批改人： David
- 最终得分:100

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共4题，每题5分，共计20分)
- note: 完美20

#### 1. 请写出你了解的机器学习特征工程操作，以及它的意义（面试题）
- note: 除纬/维外，完美

特征工程包括数据与特征处理、特征选择和降纬三部分。
#### 数据与特征处理包括：
1.数据选择、清洗、采样
- 数据格式化；
- 数据清洗，填充缺失值、去掉脏数据，将不可信的样本丢掉，缺省值极多的字段考虑不用；
- 采样：针对正负样本不平衡的情况，当正样本远大于负样本时，且量都很大时，使用下采样，量不大时，可采集更多的数据或oversampling或修改损失函数；采样过程中可利用分层抽样保持不同类别数据的比例。

2.不同类型数据的特征处理
- 数值型：幅度调整/归一化、log等变化、统计值（例如max、min、mean、std）、离散化、分桶等
- 类别型：one-hot编码等
- 时间型： 提取出连续值的持续时间和间隔时间；提取出离散值的“年”、“月”、“日”、“一年中哪个星期/季度”、“一周中的星期几”、“工作日/周末”等信息
- 文本型：使用If-idf特征
- 统计型：加减平均、分位线、次序、比例

#### 意义：
- 对数据进行预处理，可提高数据质量，提高挖掘质量。对数据进行清洗可填充缺失值、光滑噪声数据，识别和删除离群点数据，保证数据的一致性；
- 使用正确的采样方法可解决因数据不平衡带来的预测偏差；
- 对不同的数据类型进行不同的特征处理有助于提高特征的可用性，例如对数值型数据进行归一化可将数据转化到统一量纲下；对类别型数据，可用one-hot编码方法将类别数据数字化，数字化特征之后可更用来计算距离、相似性等；可从时间型数据当中提取中更多的时间特征，例如年、月和日等，这些特征对于业务场景以及模型的预测往往有很大的帮助。统计型特征处理有助于从业务场景中挖掘更丰富的信息。


#### 特征选择包括：
1.Filter<br>
使用方差、Pearson相关系数、互信息等方法过滤特征，评估单个特征和结果值之间的相关程度，留下Top相关的特征部分。

2.Wrapper
可利用“递归特征删除算法”，把特征选择看做一个特征子集搜索问题，筛选各种特征子集，用模型评估效果。

3.Embedded
可利用正则化方式选择特征，使用带惩罚项的基模型，除了选择出特征外，同时也进行了降纬。

#### 意义：
-剔除对结果预测不大的特征，减小冗余，选择有意义的特征输入模型，提高计算性能。

#### 降纬：
方法：主成分分析法（PCA）和线性判别分析（LDA）

#### 意义：
通过PCA或LDA方法，将较高纬度样本空间映射到较低维度的样本空间，从而达到降纬的目的，减少模型的训练时间，提高模型的计算性能。



#### 2.请写出上述特征工程操作的sklearn或者pandas实现方式


#### 数据与特征处理包括：
1.数据选择、清洗、采样
- 填充缺失值（pd.DataFrame.fillna()）
- 去掉脏数据pd.DataFrame.dropna()

2.不同类型数据的特征处理
- 数值型
    - 归一化 min_max_scaler.fit_transform(preprocessing.MinMaxScaler())
    - 标准化 StandardScaler().fit_transform(data)
    - 统计值：pd.Series.describe()
    - 离散化:pd.cut()
- 类别型：one-hot编码 pd.get_dummies()
- 时间型：pandas.DatetimeIndex.week、pandas.DatetimeIndex.weekday、pandas.DatetimeIndex.weekofyear、pandas.DatetimeIndex.year等

#### 特征选择包括：
1.Filter<br>
- 方差法<br>
from sklearn.feature_selection import VarianceThreshold<br>
VarianceThreshold(threshold=3).fit_transform(data)<br>

- 相关系数法<br>
from sklearn.feature_selection import SelectKBest<br>
from scipy.stats import pearsonr<br>
SelectKBest(lambda X, Y: array(map(lambda x:pearsonr(x, Y), X.T)).T, k=2).fit_transform(data, target)<br>
2.Wrapper<br>
递归特征消除法，返回特征选择后的数据，参数estimator为基模型，参数n_features_to_select为选择的特征个数<br>
from sklearn.feature_selection import RFE<br>
from sklearn.linear_model import LogisticRegression<br>
RFE(estimator=LogisticRegression(), n_features_to_select=2).fit_transform(iris.data, iris.target)<br>

3.Embedded<br>
from sklearn.feature_selection import SelectFromModel<br>
from sklearn.linear_model import LogisticRegression<br>
#带L1惩罚项的逻辑回归作为基模型的特征选择<br>
SelectFromModel(LogisticRegression(penalty="l1", C=0.1)).fit_transform(iris.data, iris.target)<br>



#### 3.模型评估中的留一法，留出法，交叉验证分别是什么操作？

#### 留一法：
假设样本数据集中有N个样本数据。将每个样本单独作为测试集，其余N-1个样本作为训练集，即每次迭代中都使用了最大可能数目的样本来训练，这样得到了N个分类器或模型，用这N个分类器或模型的分类准确率的平均数作为此分类器的性能指标。

#### 留出法：
“留出法”直接将样本数据划分成两个互斥的集合，其中一个作为训练集S，另一个作为测试集T，一般划分2/3~4/5的样本用于训练。划分方法是进行采样，按照“分层采样”的规则，训练集和测试集中正例和反例的分布必须和样本总数中分布一致，以最大限度保证数据无偏差。往往随机划分多次，取最后平均值作为评估结果。

#### 交叉验证
交叉验证的基本思想是把在某种意义下将原始数据(dataset)进行分组,一部分做为训练集，另一部分做为测试集,首先用训练集对分类器进行训练，再利用测试集来测试训练得到的模型，以此来做为评价分类器的性能指标。常见见的交叉验证形式是k折交叉验证法。<br>
K折交叉验证，将数据集分割成K份，一份被保留作为验证模型的数据，其他K-1份数据用来训练。交叉验证重复K次，每份数据集验证一次，平均K次的结果或者使用其它结合方式，最终得到一个单一估测。10折交叉验证是最常用的。另外，当k等于原始数据的样本个数时，就等同于留一法。


#### 4.如何理解模型的过拟合与欠拟合，以及如何解决？（面试题）

#### 过拟合：把样本中的一些噪声特性也学习下来了，泛化能力差。<br>
#### 欠拟合：模型没有很好地捕捉到数据特征，不能够很好地拟合数据。<br>

#### 过拟合解决办法：
- 重新清洗数据，排除噪声数据；
- 通知正则化添加参数“惩罚”，控制参数幅度；
- 限制参数搜索空间，减小过拟合风险；
- 增大数据的训练量，提高训练数据占总数据的比例。

#### 欠拟合解决办法：
- 添加提取更多的特征；
- 复杂模型，例如，添加多项式特征，将线性模型通过添加二次项或者三次项使模型泛化能力更强；
- 减少正则化参数，正则化的目的是用来防止过拟合的，但是现在模型出现了欠拟合，则需要减少正则化参数。


## 操作题(共1题，共计80分)

- note:80分。。如果能结合业务场景，再解释下模型就更完美了

### 信用卡欺诈项目(共7项，前5项每题10分，6，7题每题15分)

- 前期数据导入,预览及处理(此部分勿修改，涉及的数据文件无需复制移动)

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [2]:
data.shape

(112915, 11)

In [3]:
data.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [4]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [5]:
data.dropna(inplace=True)
data.shapey = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


In [6]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)
y.mean()

0.06742876076872101

In [7]:
print(X.shape)
print(y.shape)

(108648, 10)
(108648,)


- 1.把数据切分成训练集和测试集

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=1, train_size = 0.7)

/usr/local/lib/python3.5/dist-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [9]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(76053, 10)
(76053,)
(32595, 10)
(32595,)


- 2.使用logistic regression建模，并且输出一下系数，分析重要度。   

In [43]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
lr = Pipeline([('sc', StandardScaler()),('clf', LogisticRegression()) ])
lr.fit(x_train, y_train.ravel())

Pipeline(memory=None,
     steps=[('sc', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [44]:
lr.named_steps['clf'].intercept_

array([-2.86067075])

In [45]:
lr.named_steps['clf'].coef_

array([[-0.03249507, -0.36920706,  1.72812778,  0.30058491, -0.12269363,
        -0.11329208,  1.52279256, -0.15295176, -3.08913996,  0.09305455]])

In [46]:
lr.named_steps['clf'].n_iter_ 

array([7], dtype=int32)

In [47]:
lr.named_steps['clf'].get_params 

<bound method BaseEstimator.get_params of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)>

- 3.使用决策树/SVM/KNN...等sklearn分类算法进行分类，尝试了解参数含义，调整不同的参数。

In [15]:
#决策树
from sklearn.tree import DecisionTreeClassifier
tree_model = Pipeline([
        ('ss', StandardScaler()), #将数据标准化，预处理，保证每个特征的均值都是0 方差都是1 
        ('DTC', DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=3))]) #利用熵的准则  树的深度为3 
        #最小叶子节点的样本数必须是3及3个以上
tree_model.fit(x_train, y_train)

Pipeline(memory=None,
     steps=[('ss', StandardScaler(copy=True, with_mean=True, with_std=True)), ('DTC', DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=3, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'))])

In [ ]:
#SVM
from sklearn import svm
svm_clf = svm.SVC(C=0.8, kernel='rbf', gamma=20, decision_function_shape='ovr')  #指定decision_function_shape分三个列
svm_clf.fit(x_train, y_train.ravel())

In [ ]:
from sklearn import svm  #平台跑不出来
svm_linear = svm.SVC(C=0.3, kernel='linear')
svm_linear.fit(x_train, y_train.ravel())

In [ ]:
#SVM尝试不同的参数
clfs = [svm.SVC(C=0.3, kernel='linear'),
           svm.SVC(C=10, kernel='linear'),
           svm.SVC(C=5, kernel='rbf', gamma=1),
           svm.SVC(C=5, kernel='rbf', gamma=4)]
for i, clf in enumerate(clfs):
        clf.fit(x_train, y_train)
        y_hat = clf.predict(x)

In [ ]:
#KNN  #平台跑不出来
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2)
knn.fit(x_train, y_train)

- 4.在测试集上进行预测，计算准确度

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
#LR
y_hat_lr = lr.predict(x_test)
accuracy_score(y_test, y_hat_lr)

0.9324743058751342

In [50]:
#决策树
y_hat_tree = tree_model.predict(x_test)
accuracy_score(y_test, y_hat_tree)

0.9336708084061973

In [ ]:
#SVM 
y_hat = svm_linear.predict(x_test)
accuracy_score(y_test, y_hat)

In [ ]:
#KNN
y_hat = knn.predict(x_test)
accuracy_score(y_test, y_hat)

- 5.查看sklearn的官方说明，了解混淆矩阵等评估标准，并对此例进行评估。

In [ ]:
#混淆矩阵用来评估模型好坏
#二分类问题中，列表示预测值，行表示实际值，列包括预测为正、预测为负两列，行包括实际为正、实际为负两列
#TP：实际为正例，预测也为正例
#FN：实际为正例，错误地预测成了负例
#FP：实际为负例，错误地预测成了正例
#TN：实际为负例，预测也为负例

由于平台跑不出SVM和KNN数据，以LR和决策树为例，SVM和KNN同理可以得出

In [51]:
#LR
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_hat_lr)
#TP = 30315; FN = 56; FP = 2145; TN = 79

array([[30315,    56],
       [ 2145,    79]])

In [52]:
from sklearn.metrics import classification_report
print("LR:\n",classification_report(y_test, y_hat_lr))
#classification_report(y_test, y_hat_lr)

LR:
              precision    recall  f1-score   support

          0       0.93      1.00      0.96     30371
          1       0.59      0.04      0.07      2224

avg / total       0.91      0.93      0.90     32595



评估：该模型对负样本的预测结果较好

In [21]:
#决策树
confusion_matrix(y_test, y_hat_tree)

array([[30257,   114],
       [ 2048,   176]])

In [22]:
from sklearn.metrics import classification_report
print("DecisionTree:\n",classification_report(y_test, y_hat_tree))
#classification_report(y_test, y_hat_lr)

DecisionTree:
              precision    recall  f1-score   support

          0       0.94      1.00      0.97     30371
          1       0.61      0.08      0.14      2224

avg / total       0.91      0.93      0.91     32595



评估：该模型对负样本的预测结果较好

- 6.银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。   
比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”   
试试看把阈值设定为0.3，再看看这个时候的混淆矩阵等评估指标。

In [53]:
#0.5作为边界值，大于0.5作为一类，小于0.5作为另一类。
lr_proba = lr.predict_proba(x_test) #Returns the probability of the sample for each class in the model

In [54]:
lr_proba_r = lr_proba[:,1] > 0.3
lr_proba_r

array([False, False, False, ..., False, False, False])

In [55]:
confusion_matrix(y_test, lr_proba_r)

array([[30187,   184],
       [ 2014,   210]])

In [56]:
print("DecisionTree:\n",classification_report(y_test, lr_proba_r))

DecisionTree:
              precision    recall  f1-score   support

          0       0.94      0.99      0.96     30371
          1       0.53      0.09      0.16      2224

avg / total       0.91      0.93      0.91     32595



- 7.尝试对不同特征的重要度进行排序，通过特征选择的方式，对特征进行筛选。并重新建模，观察此时的模型准确率等评估指标。

In [57]:
from sklearn.ensemble import RandomForestClassifier #用随机森林的方法进行特征筛选
forest=RandomForestClassifier(random_state=0,n_jobs=-1)
forest.fit(x_train,y_train)
importances=forest.feature_importances_

In [58]:
import numpy as np
feat_labels=data.columns[1:]
indices=np.argsort(importances)[::-1]
for f in range(x_train.shape[1]):
    print ('%2d) %-*s %f'%(f,30,feat_labels[indices[f]],importances[indices[f]]))

 0) RevolvingUtilizationOfUnsecuredLines 0.180966
 1) DebtRatio                      0.173382
 2) MonthlyIncome                  0.160977
 3) age                            0.124103
 4) NumberOfTimes90DaysLate        0.107529
 5) NumberOfOpenCreditLinesAndLoans 0.090547
 6) NumberOfTime30-59DaysPastDueNotWorse 0.048881
 7) NumberOfDependents             0.046502
 8) NumberOfTime60-89DaysPastDueNotWorse 0.034593
 9) NumberRealEstateLoansOrLines   0.032522


In [59]:
#选择前五个特征进行建模
x_train_5 = x_train[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age','NumberOfOpenCreditLinesAndLoans']] 
x_test_5 = x_test[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age','NumberOfOpenCreditLinesAndLoans']]

lr.fit(x_train_5, y_train.ravel())

Pipeline(memory=None,
     steps=[('sc', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [61]:
y_hat_5 = lr.predict(x_test_5)
print("LR:\n",classification_report(y_test, y_hat_5))

LR:
              precision    recall  f1-score   support

          0       0.93      1.00      0.96     30371
          1       0.00      0.00      0.00      2224

avg / total       0.87      0.93      0.90     32595



/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [62]:
accuracy_score(y_test, y_hat_5) #准确度下降  选择所有特征的时候，准确度为0.9324743058751342

0.9317686761773278

选择前五个特征进行建模，无法预测出来正样本，对负样本的预测能力不变

In [63]:
#选择前七个特征
x_train_7 = x_train[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age','NumberOfOpenCreditLinesAndLoans','NumberOfTime30-59DaysPastDueNotWorse','NumberOfDependents']]
x_test_7 = x_test[['RevolvingUtilizationOfUnsecuredLines','DebtRatio','MonthlyIncome','age','NumberOfOpenCreditLinesAndLoans','NumberOfTime30-59DaysPastDueNotWorse','NumberOfDependents']]

lr.fit(x_train_7, y_train)

Pipeline(memory=None,
     steps=[('sc', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [64]:
y_hat_7 = lr.predict(x_test_7)
print("LR:\n",classification_report(y_test, y_hat_7))

LR:
              precision    recall  f1-score   support

          0       0.93      1.00      0.96     30371
          1       0.63      0.01      0.02      2224

avg / total       0.91      0.93      0.90     32595



In [65]:
accuracy_score(y_test, y_hat_7) #准确度比五个特征的高，比全特征的低些

0.9320754716981132

选择七个特征进行建模，对负样本的预测能力不变，对正样本预测，其precision指标提高，其余指标下降。

### 本阶段课程意见反馈题(5分送分项，非必答)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


### 收获
学习了积极学习算法的实操，学习了特征工程处理，基本了解了机器学习的大致流程
### 欠缺
要补的还太多，尤其是理论部分和sklearn库中各种算法的运用

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

本周进入了机器学习的重点，对于机器学习的核心部分，只用一周，显然时间太紧了

<hr>
<center><h1>####答卷结束####</h1></center>