## 七月在线机器学习实训营三期第六周(机器学习)考试
#### 考试说明:
- 起止时间：请同学在2018年3月16日至3月18日期间完成，最晚提交时间本周日（3月18日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam6后，进行作答。例如wangwei-exam6
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/4/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>李建其</u>  
- 批改人： David
- 最终得分:90

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共4题，每题5分，共计20分)

- note:15

#### 1. 请写出你了解的机器学习特征工程操作，以及它的意义（面试题）
#### 2.请写出上述特征工程操作的sklearn或者pandas实现方式

- 1.特征归一化
 - 主要是将数据缩放到一定范围内, 并将各个特征的数量级和范围进行统一, 可以避免激活函数饱和, 增加模型收敛性和精度等
- 2.One-hot Enconding
 - 将多类别的label进行编码，n各类别对应(n,)的向量，对应index上的值为1
 

- 3.处理缺失值 特征清洗
    - 通过pandas中DataFrame的fillna函数，参数可以使用values或者method
    - 使用sklearn中的Imputer
- 4.常用的特征处理方式
    - 幅度缩放，作为新的特征，比如取log，sklearn.preprocessing 中的MinMaxScaler、StandardScaler    
    - 统计结果，作为新的特征，比如 min，max，DataFrame的quantile(0.25)方法等   
    - 四则运算，作为新的特征
    - 高次特征和交叉特征，作为新的特征， 比如sklearn.preprocessing 中的PolynomialFeatures(degree=2)   
    - 离散化/分箱/分桶，作为新的特征，比如pandas中的函数cut，qcut
    - 独热向量编码，作为新的特征，比如pandas中的get_dummies函数，注意参数    
    - 时间型特征，作为新的特征， 比如使用pandas中的to_datetime函数，得到DateTime型变量后，可以使用属性 month，dayofyear，dayofweek等    
    - 多个特征时，使用降维
- 5.特征选择
    - Filter 过滤型
        - 思路：自变量和目标变量之间的关联
        - 相关系数 
            - SelectKBest：返回k个最佳特征
            - VarianceThreshold：删除特征值的方差达不到最低标准的特征
            - SelectPercentile：返回表现最佳的前r%个特征
        - 卡方校验
        - 信息增益、互信息
    - Wrapper 包裹型
        - 思路：通过目标函数（AUC/MSE）来决定是否加入一个变量
        - 迭代：产生特征子集，评价。方式有完全搜索、启发式搜索、随机搜索（GA SA）
            - RFE(递归特征消除Recursive feature elimination)
                - 对初始特征集合中每个特征赋予一个初始权重
                - 训练，将权重最小的特征消除
                - 不断迭代，直到特征集合的数目达到预定值
                - RFE的稳定性很大程度上取决于在迭代的时候底层用哪种模型
            - RFECV 在RFE训练时，增加交叉验证
    - Embededd 嵌入型
        - 思路：学习器本身自动选择特征
        - 正则化 L1（Lasso）、L2（Ridge）
        - 决策树 熵、信息增益
        - 深度学习

#### 3.模型评估中的留一法，留出法，交叉验证分别是什么操作？

- 留一法：取N个样本中的一个样本作为验证样本，其他N-1个样本作为训练样本，分别进行训练  得到N个分类器（或者回归模型），用这N分类器验证结果的平均值来评估模型参数的性能。
- 留出法：将N个样本分为训练集和验证集，按照一定的规则来区分，比如取P个样本点作为训练  集，N-P个样本点作为验证集，需要做Cnp个分类器（回归模型），对这些分类器的元整结果做平均，评估模型的性能。留出法的时间复杂度非常高。
- 交叉验证法：将样本D划分为k个大小相似的子集，每个子集尽量保持样本的分布的一致性，    
然后每次用k-1个子集做训练集，剩下的那一个子集做验证集，这样就可以获得k组训练/验证集， 分别训练模型，得到k个模型参数，对这些模型的参数的验证结果做平均，来评估模型的性能。

#### 4.如何理解模型的过拟合与欠拟合，以及如何解决？（面试题）

- 欠拟合是模型的参数学习不到位，模型的参数不足以表达当前的数据样本信息，已经不能根据样本的特征，良好的对样本指进行预测。主要原因是数据量太少，模型选择不合适等导致。

- 过拟合是在当前训练集的基础上，训练模型，为了尽可能的覆盖到每一个样本点的特征值，尤其是和样本整体的偏差较大的样本点、甚至噪声的特征，也当做有效特征来处理，最终得到一组参数，而该模型的泛化能力是比较低，或者说模型的参数对样本的特征极其敏感。而该模型由于特别的照顾每一个样本点，所以当测试集的数据和训练集不一样时，模型会出现预测不正确的情况。

## 操作题(共1题，共计80分)

- note:75

### 信用卡欺诈项目(共7项，前5项每题10分，6，7题每题15分)

- 前期数据导入,预览及处理(此部分勿修改，涉及的数据文件无需复制移动)

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [2]:
data.shape

(112915, 11)

In [3]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [4]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)
y.mean()

0.06744896603639906

In [5]:
X.shape

(112915, 10)

In [6]:
y.shape

(112915,)

### 特征处理

In [7]:
# 缺失值填充
X['age'].fillna(value=X['age'].median(),inplace=True)
X['NumberOfDependents'].ffill(inplace=True)
X.isnull().sum()

RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [8]:
# 对连续特征值做幅度缩放
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X['RUOU_std'] = stdsc.fit_transform(X[['RevolvingUtilizationOfUnsecuredLines']])
X['MI_std'] = stdsc.fit_transform(X[['MonthlyIncome']])

from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X['age_mms'] = mms.fit_transform(X[['age']])
X['NOT30DPDNW_mms'] = mms.fit_transform(X[['NumberOfTime30-59DaysPastDueNotWorse']])
X['NOOCLAL_mms'] = mms.fit_transform(X[['NumberOfOpenCreditLinesAndLoans']])
X['NOTDL_mms'] = mms.fit_transform(X[['NumberOfTimes90DaysLate']])
X['NRELOL_mms'] = mms.fit_transform(X[['NumberRealEstateLoansOrLines']])
X['NOT60DPDNW_mms'] = mms.fit_transform(X[['NumberOfTime60-89DaysPastDueNotWorse']])
X['NOD_mms'] = mms.fit_transform(X[['NumberOfDependents']])
X.head()

RevolvingUtilizationOfUnsecuredLines   age  \
0                              0.766127  45.0   
1                              0.957151  40.0   
2                              0.658180  38.0   
3                              0.233810  30.0   
4                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  RUOU_std    MI_std   age_mms  NOT30DPDNW_mms  \
0                 2.0 -0.019841  0.146138  0.436893        0.020408   
1                 1.0 -0.019092 -0.294943  0.388350        0.000000   
2                 0.0 -0.020264 -0.265042  0.368932        0.010204   
3                 0.0 -0.021929 -0.247588  0.291262        0.000000   
4                 0.0 -0.019287  3.830924  0.475728        0.010204   

   NOOCLAL_mms  NOTDL_mms  NRELOL_mms  NOT60DPDNW_mms  NOD_mms  
0     0.228070   0.000000    0.206897             0.0     0.10  
1     0.070175   0.000000    0.000000             0.0     0.05  
2     0.035088   0.010204    0.000000             0.0     0.00  
3     0.087719   0.000000    0.000000             0.0     0.00  
4     0.122807   0.000000    0.034483             0.0     0.00

In [9]:
X_scale = X.drop(['RevolvingUtilizationOfUnsecuredLines',
                   'MonthlyIncome','age','NumberOfTime30-59DaysPastDueNotWorse',
                  'NumberOfOpenCreditLinesAndLoans','NumberOfTimes90DaysLate',
                  'NumberRealEstateLoansOrLines',
                   'NumberOfTime60-89DaysPastDueNotWorse','NumberOfDependents'],axis=1)
X_scale.head()

DebtRatio  RUOU_std    MI_std   age_mms  NOT30DPDNW_mms  NOOCLAL_mms  \
0   0.802982 -0.019841  0.146138  0.436893        0.020408     0.228070   
1   0.121876 -0.019092 -0.294943  0.388350        0.000000     0.070175   
2   0.085113 -0.020264 -0.265042  0.368932        0.010204     0.035088   
3   0.036050 -0.021929 -0.247588  0.291262        0.000000     0.087719   
4   0.024926 -0.019287  3.830924  0.475728        0.010204     0.122807   

   NOTDL_mms  NRELOL_mms  NOT60DPDNW_mms  NOD_mms  
0   0.000000    0.206897             0.0     0.10  
1   0.000000    0.000000             0.0     0.05  
2   0.010204    0.000000             0.0     0.00  
3   0.000000    0.000000             0.0     0.00  
4   0.000000    0.034483             0.0     0.00

In [10]:
X_scale.shape

(112915, 10)

- 1.把数据切分成训练集和测试集

In [11]:
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version

if Version(sklearn_version) < '0.18':
    from sklearn.cross_validation import train_test_split
else:
    from sklearn.model_selection import train_test_split
    
X_train,X_test,y_train,y_test = train_test_split(X_scale,y,test_size=0.3,random_state=42)

- 2.使用logistic regression建模，并且输出一下系数，分析重要度。   

In [12]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
# log_reg = LogisticRegression(C=0.1)
log_reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
log_reg.coef_

array([[ 1.43539004, -0.02313205, -0.15142919, -2.63755828,  8.89298272,
        -1.38629688,  3.65358123, -4.01189881, -8.55685841,  1.9578994 ]])

In [14]:
log_reg.intercept_

array([-1.63613529])

- 3.使用决策树/SVM/KNN...等sklearn分类算法进行分类，尝试了解参数含义，调整不同的参数。

In [15]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

y_test_pred = log_reg.predict(X_test)
y_train_pred = log_reg.predict(X_train)

print('MAE train: %.3f, test: %.3f' % (
        mean_absolute_error(y_train, y_train_pred),
        mean_absolute_error(y_test, y_test_pred)))
print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MAE train: 0.068, test: 0.065
MSE train: 0.068, test: 0.065
R^2 train: -0.070, test: -0.066
accuracy train: 0.932, test: 0.935


- 4.在测试集上进行预测，计算准确度

In [16]:
#决策树
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)
tree.fit(X_train,y_train)

y_test_pred = tree.predict(X_test)
y_train_pred = tree.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.065, test: 0.064
R^2 train: -0.029, test: -0.040
accuracy train: 0.935, test: 0.936


In [17]:
#决策树
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='entropy',max_depth=10,random_state=0)
tree.fit(X_train,y_train)

y_test_pred = tree.predict(X_test)
y_train_pred = tree.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.057, test: 0.066
R^2 train: 0.104, test: -0.081
accuracy train: 0.943, test: 0.934


In [ ]:
#SVM
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma=0.2, C=1.0)
svm.fit(X_train, y_train)

y_test_pred = svm.predict(X_test)
y_train_pred = svm.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

In [115]:
#SVM
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma=0.2, C=0.01)
svm.fit(X_train, y_train)

y_test_pred = svm.predict(X_test)
y_train_pred = svm.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))

MSE train: 0.068, test: 0.066
R^2 train: -0.073, test: -0.070


In [113]:
#SVM
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma=0.2, C=0.001)
svm.fit(X_train, y_train)

y_test_pred = svm.predict(X_test)
y_train_pred = svm.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.068, test: 0.066
R^2 train: -0.073, test: -0.070
accuracy train: 0.932, test: 0.934


In [112]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5,p=2,metric='minkowski')
knn.fit(X_train,y_train)

y_test_pred = knn.predict(X_test)
y_train_pred = knn.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.065, test: 0.068
R^2 train: -0.022, test: -0.104
accuracy train: 0.935, test: 0.932


In [111]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5,p=3,metric='minkowski')
knn.fit(X_train,y_train)

y_test_pred = knn.predict(X_test)
y_train_pred = knn.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.065, test: 0.068
R^2 train: -0.018, test: -0.115
accuracy train: 0.935, test: 0.932


In [110]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=2,p=2,metric='minkowski')
knn.fit(X_train,y_train)

y_test_pred = knn.predict(X_test)
y_train_pred = knn.predict(X_train)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

MSE train: 0.060, test: 0.068
R^2 train: 0.051, test: -0.115
accuracy train: 0.940, test: 0.932


- 5.查看sklearn的官方说明，了解混淆矩阵等评估标准，并对此例进行评估。

In [18]:
'''
混淆矩阵  可以直观表现在正例和反例上的表现，
包括真正例个数，假正例个数，假反例个数，真反例个数
以及可以计算准确率，召回率。假反例的个数为2201，偏高，
真反例的个数很低。
'''
from sklearn.metrics import confusion_matrix


y_test_pred = log_reg.predict(X_test)
y_train_pred = log_reg.predict(X_train)

print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

confusion_matrix(y_test, y_test_pred)

accuracy train: 0.932, test: 0.935


array([[31637,    14],
       [ 2201,    23]])

- 6.银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。   
比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”   
试试看把阈值设定为0.3，再看看这个时候的混淆矩阵等评估指标。

In [19]:
log_reg = LogisticRegression(class_weight={0:0.7,1:0.3})
log_reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight={0: 0.7, 1: 0.3}, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [20]:
# 修改敏感度之后，假反例的个数升高，
# 真反例的个数降低，准确度基本不变。
y_test_pred = log_reg.predict(X_test)
y_train_pred = log_reg.predict(X_train)
print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

confusion_matrix(y_test, y_test_pred)

accuracy train: 0.932, test: 0.934


array([[31640,    11],
       [ 2211,    13]])

- 7.尝试对不同特征的重要度进行排序，通过特征选择的方式，对特征进行筛选。并重新建模，观察此时的模型准确率等评估指标。

In [23]:
from sklearn.ensemble import RandomForestClassifier

feat_labels = X_train.columns
forest = RandomForestClassifier(n_estimators=10,
                               random_state=0,
                               n_jobs=-1)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=-1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [22]:
forest.feature_importances_

array([ 0.17196004,  0.18949931,  0.16155268,  0.11889458,  0.04857167,
        0.08869302,  0.11064335,  0.031732  ,  0.03192375,  0.04652961])

In [25]:
import numpy as np
importances = forest.feature_importances_
indices = np.argsort(importances)[::-1]# np.argsort返回从小到大排列所对应的索引值，对索引值逆序
for f in range(X_train.shape[1]):
    print('%2d) %-*s %f' % (f+1, 30, 
                            feat_labels[indices[f]],
                            importances[indices[f]]))

 1) RUOU_std                       0.189499
 2) DebtRatio                      0.171960
 3) MI_std                         0.161553
 4) age_mms                        0.118895
 5) NOTDL_mms                      0.110643
 6) NOOCLAL_mms                    0.088693
 7) NOT30DPDNW_mms                 0.048572
 8) NOD_mms                        0.046530
 9) NOT60DPDNW_mms                 0.031924
10) NRELOL_mms                     0.031732


In [38]:
# 根据重要度排序 挑选排名前5的特征来进行训练
X_sort6 = X_scale[['RUOU_std','DebtRatio','MI_std','age_mms','NOTDL_mms','NOOCLAL_mms']]
X_train,X_test,y_train,y_test = train_test_split(X_sort6,y,test_size=0.3,random_state=42)

log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

y_train_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)

print('accuracy train: %.3f, test: %.3f' % (
        accuracy_score(y_train, y_train_pred),
        accuracy_score(y_test, y_test_pred)))

confusion_matrix(y_test, y_test_pred)

accuracy train: 0.932, test: 0.935


array([[31637,    14],
       [ 2201,    23]])

### 本阶段课程意见反馈题(5分送分项，非必答)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


- 答：这次对使用sklearn包完成机器学习任务的流程有整体的了解，熟悉一些基本的函数使用。   但是对算法各个参数意义，以及使用场景不太明确，需要花时间搞清楚这些事情。

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

- 答：课程感觉有点紧张，学习起来有点吃力，有可能是算法知识功底不足的原因，这周的课程明显感觉在强度和难度上拔升了一个level。

<hr>
<center><h1>####答卷结束####</h1></center>