## 七月在线机器学习实训营三期第七周(机器学习-模型调优与融合)考试
#### 考试说明:
- 起止时间：请同学在2018年3月23日至3月25日期间完成，最晚提交时间本周日（3月25日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学<font color=red><b>拷贝</b></font>该试卷至自己姓名的目录后，将文件更名为同学姓名拼音-exam7后，进行作答。例如wangwei-exam7
- 提交格式：请同学新建自己姓名全拼的文件夹，将该试卷，数据文件，zip文件等相关考试文件，放置此目录下。将该目录<b>移动</b>至/0.Teacher/Exam/7/目录下
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:<u>__陈益梦__</u>  
- 批改人： David
- 最终得分: 93

<center><h1>####答卷开始####</h1></center>
<hr>

## 简答题(共6题，1，2题每题5分，后4题每题10分，共计50分)

- note:43

#### 1. 机器学习任务中，通常会将给定数据切分为训练集，验证集，测试集，请回答这三类数据集各自的用途。

- 训练集 (training set):数据集的子集，用于训练模型。

- 验证集 (validation set):数据集的一个子集，从训练集分离而来，用于调整超参数。

- 测试集 (test set):数据集的子集，用于在模型经由验证集的初步验证之后测试模型，评估模型的泛化能力。

#### 2.如何将数据转换成xgboost内置用法的libsvm数据格式，以及该格式数据是如何解读的?

- note:libsvm格式解读没有？

- 使用xgboost内置的DMatrix方法可以加载libsvm数据格式

In [1]:
# 输入文件 --> 第一列需要时 label，得到libsvm 格式的数据文件
def transform_txt_to_libsvm(input_file, output_file, separator):
    # transform data.txt to libsvm type data, get libsvm.txt  
    
    #read data file  
    with open(input_file, 'r') as readin:
        #write data file  
        with open(output_file, 'w') as output:
            try:  
                the_line = readin.readline()  
                while the_line:  
                    # delete the \n  
                    the_line = the_line.strip('\n')  
                    index = 0;  
                    output_line = ''  
                    for sub_line in the_line.split(separator):  
                        #the label col  
                        if index == 0:  
                            output_line = sub_line  
                        #the features cols  
                        if sub_line != 'NULL' and index != 0:  
                            the_text = ' ' + str(index) + ':' + sub_line  
                            output_line = output_line + the_text  
                        index = index + 1  
                    output_line = output_line + '\n'  
                    output.write(output_line)  
                    the_line = readin.readline()  
            finally:  
                readin.close()

In [2]:
transform_txt_to_libsvm('data.txt', 'libsvm.txt',',')

In [3]:
with open('data.txt', 'r') as readin:
    print('txtFile:data.txt ========================================start=======================')
    for line in readin:
        print(line)
    print('\n')
with open('libsvm.txt', 'r') as readin:
    print('txtFile:libsvm.txt  ========================================start=======================')
    for line in readin:
        print(line)

txtFile:data.txt ========================================start=======================
0,aa,bb,cc,dd

1,ab,cd,ef,gh

8,ef,gh,ij,kl

0,a,b,c,d

3,e,f,g,h

1,i,j,k,l

3,,f,,

3,,,,

1,,h,t,

1,,,,g

1,NULL,NULL,NULL,F


txtFile:libsvm.txt  ========================================start=======================
0 1:aa 2:bb 3:cc 4:dd

1 1:ab 2:cd 3:ef 4:gh

8 1:ef 2:gh 3:ij 4:kl

0 1:a 2:b 3:c 4:d

3 1:e 2:f 3:g 4:h

1 1:i 2:j 3:k 4:l

3 1: 2:f 3: 4:

3 1: 2: 3: 4:

1 1: 2:h 3:t 4:

1 1: 2: 3: 4:g

1 4:F



In [4]:
#上面打印的libsvm.txt 文件内容就是libsvm 数据格式，第一列为类别

In [5]:
#使用xgboost读取数据
import xgboost as xgb
dtrain = xgb.DMatrix('libsvm.txt')

In [6]:
dtrain.num_col()

5

In [7]:
dtrain.num_row()

11

#### 3. 对于自动特征选择，通常有哪三类方法？试写出每类方式的思想，以及在sklearn中的代码实现（面试题）

- note: 思想 ？

#### 自动特征选择：
- 过滤式（Filter） sklearn.feature_selection import SelectKBest
- 包裹式（Wrapper） sklearn.feature_selection import RFE
- 嵌入式（Embedded） sklearn.ensemble import ExtraTreesClassifie

#### Filter

In [8]:
from sklearn.feature_selection import SelectKBest,SelectPercentile
from sklearn.datasets import load_iris

In [9]:
iris = load_iris()
X, y = iris.data, iris.target
# SelectKBest：选择排名前k个的特征
model_select_best = SelectKBest(k=3).fit(X,y)
X_select_best = model_select_best.transform(X)
# SelectPercentile：选择排名在前k%的特征
model_select_percentile = SelectPercentile(percentile=80).fit(X,y)
X_select_percentile = model_select_percentile.transform(X)

In [10]:
X.shape

(150, 4)

In [11]:
X_select_best.shape

(150, 3)

In [12]:
model_select_best.get_support()

array([ True, False,  True,  True], dtype=bool)

In [13]:
X_select_percentile.shape

(150, 3)

In [14]:
model_select_percentile.get_support()

array([ True, False,  True,  True], dtype=bool)

In [15]:
# 设置一个方差阈值，没有达到这个方差阈值的特征都会被丢弃
from sklearn.feature_selection import VarianceThreshold
model_v = VarianceThreshold(threshold=0.5).fit(X,y)
X_select_v = model_v.transform(X)

In [16]:
X_select_v.shape

(150, 3)

In [17]:
model_v.get_support()

array([ True, False,  True,  True], dtype=bool)

#### Wrapper

In [18]:
# 指定一个学习算法，通过算法计算所有子集的error，选择error最小的子集作为选取的特征
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [19]:
rf = RandomForestClassifier()
rfe = RFE(estimator=rf, n_features_to_select=3)
X_rfe = rfe.fit_transform(X,y)

In [20]:
X_rfe.shape

(150, 3)

In [21]:
rfe.support_

array([ True, False,  True,  True], dtype=bool)

#### Embedded

In [22]:
# LinearSVC选取特征
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC

In [23]:
# 参数C控制特征系数稀疏度，C的值越小，选择的特征数越少
lsvc = LinearSVC(C=0.01, penalty='l1', dual=False).fit(X, y)

In [24]:
model = SelectFromModel(lsvc, prefit=True)

In [25]:
X_select_from_lsvc = model.transform(X)
X_select_from_lsvc.shape

(150, 3)

In [26]:
lsvc.coef_

array([[ 0.        ,  0.21678422, -0.28726535,  0.        ],
       [ 0.        , -0.09186784,  0.        ,  0.        ],
       [-0.0348547 , -0.17041784,  0.13476597,  0.        ]])

In [27]:
model.get_support()

array([ True,  True,  True, False], dtype=bool)

##### 通过对比，filter 里面的方差选择法和相关系数法 和 Wrapper的随机森林迭代包裹删除法 删除的是第二个特征；Embedded LinearSVC选取特征 删除的是第四个特征
##### Embedded 方法加了正则化。。。。。

#### 4.网格搜索交叉验证的作用是什么，并简述网格搜索交叉验证是如何运行的？ 

- **作用：** 网格搜索交叉验证是遍历给定的参数组合，然后进行交叉验证，找出使交叉验证精确度最高的参数组合，来优化模型表现。



- **运行：**
以决策树为例，给定一组参数 {'max_depth': [1,2,3,4,5]}，3折交叉验证。

In [28]:
# for d in max_depth:
#   for i in rang(3):
#     计算深度为 d 时候，3折交叉验证的第i次运算，得到结果 p
#   深度为d 的运算结果为sum(p)/3
# 得到深度为 1,2,3,4,5 的时候的5个结果，选取分数最高的

#### 5.工业界上模型整合有三大类方式？试简述每类方式其思想？（面试题）

#### 模型整合：Bagging，Boosting，Stacking

##### Bagging
Bagging就是采用有放回的方式进行抽样，用抽样的样本建立子模型,对子模型进行训练，这个过程重复多次，最后进行融合。<br>
大概分为这样两步：<br>
1、重复K次<br>
有放回地重复抽样建模<br>
训练子模型<br>
2.模型融合<br>
分类问题：voting<br>
回归问题：average<br>
可以是异质模型，并行处理。<br>
##### Boosting
Boosting的思想是一种迭代的方法，每一次训练的时候都更加关心分类错误的样例，给这些分类错误的样例增加更大的权重，下一次迭代的目标就是能够更容易辨别出上一轮分类错误的样例。最终将这些弱分类器进行加权相加。<br>
在boosting中，总是试图添加新模型以纠正先前模型的弱点。因此它是顺序串行的。<br>
##### Stacking
Stacking模型本质上是一种分层的结构，使用多个模型对训练集和测试集进行训练和预测，将得到的结果作为测试集，原本的标签作为训练集，输入到新的模型中训练，用整个训练集训练的模型反过来去预测训练集的标签，会产生过拟合，加入K折交叉验证得到最终结果。<br>


#### 6.  我们可以将xgboost的中众多参数分类为哪三类？请写出哪些参数可以用什么方式用来控制过拟合？

**三类参数**：通用参数/general parameters, 集成(增强)参数/booster parameters 和 任务参数/task parameters
- eta [default=0.3, 可以视作学习率]<br>
为了防止过拟合，更新过程中用到的收缩步长。在每次提升计算之后，算法会直接获得新特征的权重。 eta通过缩减特征的权重使提升计算过程更加保守。缺省值为0.3  取值范围为：[0,1]
- max_depth [default=6]<br>
用于设置树的最大深度!越大越容易过拟合！
- min_child_weight [default=1]<br>
表示子树观测权重之和的最小值，如果树的生长时的某一步所生成的叶子结点，其观测权重之和小于min_child_weight，那么可以放弃该步生长，在线性回归模式中，这仅仅与每个结点所需的最小观测数相对应。该值越大，算法越保守，最小的孩子集合，小于这个数，不进行接下来的切分!越小越容易过拟合。
- subsample [default=1]<br>
表示观测的子样本的比率，将其设置为0.5意味着xgboost将随机抽取一半观测用于树的生长，这将有助于防止过拟合现象
- colsample_bytree [default=1]<br>
表示用于构造每棵树时变量的列采样比率!
- scale_pos_weight, [default=1]<br>
在各类别样本十分不平衡时，把这个参数设定为一个正值，可以使算法更快收敛!

## 实验题(共2题，每题25分，共计50分)

- note:50

### 1. 使用XGBoost内置方式，导入iris数据完成分类问题（要求以不同参数设置xgboost运行并比对），最后给出实验总结

#### 导入使用库和样本数据

In [29]:
import xgboost as xgb
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()

#### 切分数据集并查看数据集形状

In [30]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=0)

In [31]:
X_train.shape

(105, 4)

In [32]:
y_train.shape

(105,)

In [33]:
X_test.shape

(45, 4)

In [34]:
y_test.shape

(45,)

#### XGBOOST 初始化数据集

In [35]:
d_train = xgb.DMatrix(data=X_train, label=y_train)
d_test = xgb.DMatrix(data=X_test, label=y_test)

In [36]:
watch_list = [(d_test, 'eval'), (d_train, 'train')]

### 第一组参数测试结果

In [37]:
param1 = {
    'eta': 0.01,
    'max_depth': 3,
    'gamma':0.1,
    'min_child_weight': 3,
    'subsample': 0.7,
    'colsample_bytree': 0.5,
#     'lambda':2,
#     'scale_pos_weight': 1,    #此处没有效果
    'objectice': 'multi:softmax',
    'num_class': 3,
    'seed': 1000
#     'eval_metric': 'auc'    # 使用这个会报错 
}
num_round1 = 10
bst1 = xgb.train(param1, d_train, num_round1, watch_list)

[0]	eval-merror:0.088889	train-merror:0.038095
[1]	eval-merror:0.088889	train-merror:0.038095
[2]	eval-merror:0.088889	train-merror:0.038095
[3]	eval-merror:0.088889	train-merror:0.028571
[4]	eval-merror:0.044444	train-merror:0.028571
[5]	eval-merror:0.022222	train-merror:0.028571
[6]	eval-merror:0.022222	train-merror:0.028571
[7]	eval-merror:0.022222	train-merror:0.047619
[8]	eval-merror:0.022222	train-merror:0.047619
[9]	eval-merror:0.022222	train-merror:0.028571


In [38]:
'''
Importance type can be defined as:
        'weight' - the number of times a feature is used to split the data across all trees.
        'gain' - the average gain of the feature when it is used in trees
        'cover' - the average coverage of the feature when it is used in trees
        
bst1.get_fscore()  # Get feature importance of each feature.
'''
bst1.get_score()

{'f0': 12, 'f1': 4, 'f2': 26, 'f3': 19}

In [39]:
bst1_cross_v = xgb.cv(param1, d_train, num_round1,nfold=3)
bst1_cross_v

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.066666         0.026937           0.042857          0.020203
1          0.057143         0.023329           0.033333          0.006734
2          0.066666         0.026937           0.028571          0.000000
3          0.066666         0.026937           0.038095          0.013469
4          0.076190         0.013468           0.038095          0.013469
5          0.066666         0.026937           0.033333          0.006734
6          0.076190         0.013468           0.033333          0.006734
7          0.076190         0.013468           0.028571          0.000000
8          0.066666         0.026937           0.028571          0.000000
9          0.066666         0.026937           0.028571          0.000000

In [40]:
import numpy as np
bst1_cross_v.agg(np.mean)

test-merror-mean     0.068571
test-merror-std      0.022536
train-merror-mean    0.033333
train-merror-std     0.006734
dtype: float64

### 第二组参数测试结果

In [41]:
param2 = {
    'eta': 0.01,   #（增大学习率到0.1会增加交叉验证的0.004 的误差）
    'max_depth': 3,
    'gamma':0.1,
    'min_child_weight': 3,
    'subsample': 0.7,
    'colsample_bytree': 0.5,  #（由 0.5 增加为0.9  会增大交叉验证的0.002 的误差）
    'lambda':2,  #增加正则  （会减小交叉验证的0.007误差）
    'objectice': 'multi:softmax',
    'num_class': 3,
    'seed': 100   #此处做修改，由 1000 减小为100
}
num_round2 = 10
bst2 = xgb.train(param1, d_train, num_round2, watch_list)

[0]	eval-merror:0.088889	train-merror:0.038095
[1]	eval-merror:0.088889	train-merror:0.038095
[2]	eval-merror:0.088889	train-merror:0.038095
[3]	eval-merror:0.088889	train-merror:0.028571
[4]	eval-merror:0.044444	train-merror:0.028571
[5]	eval-merror:0.022222	train-merror:0.028571
[6]	eval-merror:0.022222	train-merror:0.028571
[7]	eval-merror:0.022222	train-merror:0.047619
[8]	eval-merror:0.022222	train-merror:0.047619
[9]	eval-merror:0.022222	train-merror:0.028571


In [42]:
bst2_cross_v = xgb.cv(param2, d_train, num_round2,nfold=3)
bst2_cross_v

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.047619         0.026937           0.038095          0.006734
1          0.047619         0.026937           0.033333          0.006734
2          0.066667         0.013468           0.023809          0.006734
3          0.057143         0.023329           0.033333          0.017817
4          0.057143         0.023329           0.028571          0.011664
5          0.066667         0.013468           0.028571          0.000000
6          0.066667         0.013468           0.023809          0.006734
7          0.066667         0.013468           0.028571          0.000000
8          0.057143         0.023329           0.033333          0.006734
9          0.057143         0.023329           0.033333          0.006734

In [43]:
import numpy as np
bst2_cross_v.agg(np.mean)

test-merror-mean     0.059047
test-merror-std      0.020106
train-merror-mean    0.030476
train-merror-std     0.006989
dtype: float64

### 第三组参数测试结果

In [44]:
param3 = {
    'eta': 0.01,
    'max_depth': 3,
    'gamma':0.1,
    'min_child_weight': 5,   # 增大每棵树最小节点数会增大交叉验证误差0.02
    'subsample': 0.5,
    'colsample_bytree': 0.5,
    'lambda':1,
    'objectice': 'multi:softmax',
    'num_class': 3,
    'seed': 100 
}
num_round3 = 10
bst3 = xgb.train(param1, d_train, num_round3, watch_list)

[0]	eval-merror:0.088889	train-merror:0.038095
[1]	eval-merror:0.088889	train-merror:0.038095
[2]	eval-merror:0.088889	train-merror:0.038095
[3]	eval-merror:0.088889	train-merror:0.028571
[4]	eval-merror:0.044444	train-merror:0.028571
[5]	eval-merror:0.022222	train-merror:0.028571
[6]	eval-merror:0.022222	train-merror:0.028571
[7]	eval-merror:0.022222	train-merror:0.047619
[8]	eval-merror:0.022222	train-merror:0.047619
[9]	eval-merror:0.022222	train-merror:0.028571


In [45]:
bst3_cross_v = xgb.cv(param3, d_train, num_round3,nfold=3)
bst3_cross_v

test-merror-mean  test-merror-std  train-merror-mean  train-merror-std
0          0.095238         0.053875           0.090476          0.024281
1          0.076190         0.067344           0.071429          0.023329
2          0.095238         0.053875           0.066667          0.017817
3          0.085714         0.061722           0.066667          0.017817
4          0.085714         0.069986           0.052381          0.013469
5          0.095238         0.058709           0.066667          0.017817
6          0.085714         0.069986           0.057143          0.011664
7          0.085714         0.069986           0.052381          0.006734
8          0.066667         0.048562           0.057143          0.011664
9          0.066667         0.048562           0.057143          0.011664

In [46]:
import numpy as np
bst3_cross_v.agg(np.mean)

test-merror-mean     0.083810
test-merror-std      0.060261
train-merror-mean    0.063810
train-merror-std     0.015626
dtype: float64

### 网格搜索

In [50]:
from sklearn.grid_search import GridSearchCV

In [48]:
param4 = {
    'n_estimators':[100,200,500,1000],
    'learning_rate':[0.1, 0.01,0.0001],
    'max_depth': [2,3,4,5],
    'gamma':[0.01,0.1,1],
    'min_child_weight': [2,3,4],
    'subsample': [0.5,0.7],
    'colsample_bytree': [0.5,0.7],
    'seed': [100,1000]
}

clf = GridSearchCV(xgb.XGBClassifier(objectice='multi:softmax', num_class=3), param_grid=param4, cv=3)
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, num_class=3, objectice='multi:softmax',
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=True,
       subsample=1),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [100, 200, 500, 1000], 'learning_rate': [0.1, 0.01, 0.0001], 'max_depth': [2, 3, 4, 5], 'gamma': [0.01, 0.1, 1], 'min_child_weight': [2, 3, 4], 'subsample': [0.5, 0.7], 'colsample_bytree': [0.5, 0.7], 'seed': [100, 1000]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [49]:
from sklearn import metrics
print(clf.best_params_)
y_true, y_pred = y_test, clf.predict(X_test)
print("Accuracy : %.4g" % metrics.accuracy_score(y_true, y_pred)) 
print("r2_score : %.4g" % metrics.r2_score(y_true, y_pred)) 

{'colsample_bytree': 0.5, 'gamma': 0.01, 'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 2, 'n_estimators': 500, 'seed': 1000, 'subsample': 0.7}
Accuracy : 0.9778
r2_score : 0.9622


In [51]:
clf.best_params_

{'colsample_bytree': 0.5,
 'gamma': 0.01,
 'learning_rate': 0.01,
 'max_depth': 3,
 'min_child_weight': 2,
 'n_estimators': 500,
 'seed': 1000,
 'subsample': 0.7}

- 使用网格搜索得到网格中最佳参数：'colsample_bytree': 0.5, 'gamma': 0.01, 'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 2, 'n_estimators': 500, 'seed': 1000, 'subsample': 0.7

### 2. 使用XGBoost的sklearn接口，对KaggleCredit2数据完成信用卡欺诈项目的建模及分析（要求以不同参数设置xgboost运行并比对），最后给出实验总结

- KaggleCredit2数据文件 位于/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip，请勿复制或移动该文件

### 读取文件

In [1]:
import pandas as pd
import zipfile
# with zipfile.ZipFile('/home/sxy-s3/0.Teacher/Exam/KaggleCredit2.csv.zip', 'r') as z:  
with zipfile.ZipFile('KaggleCredit2.csv.zip', 'r') as z:  
    f = z.open('KaggleCredit2.csv')  
    data = pd.read_csv(f, index_col=0)  
data.head()  

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [2]:
data['SeriousDlqin2yrs'].value_counts()

0    105299
1      7616
Name: SeriousDlqin2yrs, dtype: int64

In [3]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn import metrics

In [4]:
# 样本不均衡会造成的影响
# X_train_Credit, X_test_Credit, y_train_Credit, y_test_Credit = train_test_split(data.iloc[:,1:], data['SeriousDlqin2yrs'], test_size=0.3, random_state=0)

In [5]:
# 分层随机拆分
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np
#此处必须用numpy 否则会报错
sss = StratifiedShuffleSplit(n_splits=2, test_size=0.3, random_state=0)
X = np.array(data.iloc[:,1:])
y = np.array(data['SeriousDlqin2yrs'])

sss.get_n_splits(X,y)
for train_index, test_index in sss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


In [6]:
y_train.shape

(79040,)

In [7]:
y_test.shape

(33875,)

### 第一组参数测试

In [69]:
param1 = {
    'max_depth': 4,
    'n_estimators':100,
    'learning_rate':0.01,
    'gamma':0.1,
    'min_child_weight': 4,
    'subsample': 0.8,
    'colsample_bytree': 0.5,
    'seed': 100
}

In [70]:
xgbclassifiter1 = xgb.XGBClassifier(**param1)
model1 = xgbclassifiter1.fit(X_train, y_train)

y_true, y_pred = y_test, model1.predict(X_test)
print("Accuracy : %.4g" % metrics.accuracy_score(y_true, y_pred)) 
print("r2_score : %.4g" % metrics.r2_score(y_true, y_pred)) 
fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred, pos_label=1)
print("auc : %.4g" % metrics.auc(fpr, tpr)) 

Accuracy : 0.9348
r2_score : -0.0362
auc : 0.5284


### 第二组参数测试

In [118]:
param2 = {
    'max_depth': 5,   #修改树深度 4 ->5
    'n_estimators':300, #修改最大树个数  100 -> 300  增加到500的时候会提高 acc 0.01，但是auc 会降低0.02
    'learning_rate':0.2, # 学习率 0.01 -> 0.1 没有变化，  提高到0.2 的时候，acc提高0.02，auc 下降0.012
    'gamma':0.1,   # 0.1 -> 0.2 降低auc 0.003
    'min_child_weight': 50,  #如果减小最小个数，10 -> 2，准确率降低0.01   越小越容易过拟合
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'seed': 100,  #100 -> 1000 降低acc 0.003, 提升auc 0.004  改为500 的时候降低acc 0.005，降低auc0.01
    'eval_metric': 'auc',   #增加这个参数准确度提高0.01
    'reg_lambda': 2,   #使用正则2比1准确度提升0.0008，auc提高0.002
    'scale_pos_weight': 10    #1 -> 10 导致准确率较低 0.08， auc 上升0.14   更高的时候会降低auc
}

In [119]:
xgbclassifiter2 = xgb.XGBClassifier(**param2)
model2 = xgbclassifiter2.fit(X_train, y_train)

y_true, y_pred = y_test, model2.predict(X_test)
print("Accuracy : %.4g" % metrics.accuracy_score(y_true, y_pred)) 
print("r2_score : %.4g" % metrics.r2_score(y_true, y_pred)) 
fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred, pos_label=1)
print("auc : %.4g" % metrics.auc(fpr, tpr))

Accuracy : 0.8543
r2_score : -1.316
auc : 0.7524


#### 通过增加树深度和最大树个数到一定的值，数据量大的时候学习率不能太小，正负样本比例差别很大的时候，需要配置scale_pos_weight 很重要

### 网格搜索

In [8]:
param3 = {
    'max_depth': [4,6],
    'n_estimators':[300,500],
    'learning_rate':[0.1, 0.01],
    'gamma':[0.1,0.2],
    'min_child_weight': [50,100,20],
    'subsample': [0.5,0.8],
    'colsample_bytree': [0.5,0.8],
    'seed': [100,500]
}

In [ ]:
clf = GridSearchCV(xgb.XGBClassifier(scale_pos_weight=1, subsample=0.8,), param_grid=param3, cv=3)
clf.fit(X_train,y_train)

In [ ]:
pd.DataFrame(clf.cv_results_)

### 本阶段课程意见反馈题(非必答，不送分)
#### 请同学围绕以下两点进行回答：
- 自身总结：请您对您自己在本周课程的学习，收获，技能掌握等方面进行一次总结 ，也包括有哪些方面存在哪些不足，欠缺，困惑。作为将来回顾学习路径时的依据。


学习：针对寒老师将的案例，对整个项目有了一定的了解，建立了整个学习过程的框架，学习了数据处理大致流程，针对特征的处理对模型的结果又很大影响。<br>
** 缺点：时间紧，任务重，基础差。**

- 课程反馈：请就知识点，进度，难易度，教学方式，考试方式及难易度等方面向我们反馈，督促我们进行更有效的改进。

暂无

<hr>
<center><h1>####答卷结束####</h1></center>